### ISSUE TITLE
Multiple Accounts not working

### ISSUE THREAD

**Issue by Shogunz1** [mchristopher/PokemonGo-DesktopMap#1021]
I want to run two accounts like i used to but I can only run one. When I bring up the app and login with my second acct it overtakes the scanning location of the first one and takes over the workers. Never ran into this problem before. Any tips? I usually right click the program and bring up a new instance and log in with the second acct. Worked fine before.

**Comment by nopejusttesting** [comment]
I'm having the same problem on 50% of my accounts. It's making it really difficult to set up a proper scanning sweep. A keep getting an error as well.

**Comment by NickIxo** [comment]
Yes im getting the error about ports being in use or whatever. (so that 2 scanners are using the same data or whatever. A restart used to fix it now, can't see a work around. would love some help.

**Comment by NickIxo** [comment]
Actually guys I found this to be working for me. Bear with me as it may get complicated. Im using 7 scanners. And for awhile I noticed that when logging in, my 2nd log in would give me the error and be the same spawn point on my previous log in. To me this has shown me that log ins, for some reason, are being paired with eachother.

So how i circumvented the limit, is to log in with 1 account, move its position. Then open 2 windows. Log into account 2 (error) then log into account 2 again (no error, fresh marker). leave your "junk" windows open because if you close them, you will need to log in again to fill this pair spot. (e.g. you will need to log in two times to get two errors, and the third will work, but this will compound as you log in with more scanners). 

when you're done just close all your junk windows and you should have nothing but remaining, working scanners open. I hope this helps someone! :)

**Comment by Shogunz1** [comment]
Ty so much that worked.
