### ISSUE TITLE
Account banned the second I logged in

### ISSUE THREAD

**Issue by romanticheart** [mchristopher/PokemonGo-DesktopMap#1023]
Was using the older version just this morning. Closed the old one, downloaded the new one, logged in, boom. Banned. I don't know if this is just a coincidence, but it was my last verified account so now I'm bummed. Nox isn't letting me sign in to verify, too paranoid to do it on my phone. My scanning days may be over!

**Comment by brianguy1** [comment]
I had the exact same thing happen. I upgraded and noticed the google login button was missing so I created a PTC account. I tried logging in using the PTC account and it says possible ban. I presume it is saying this because it is having issues reaching the server as it is unlikely they would have banned the account within the 5 minutes of the upgrade. I checked to make sure the API was from the same account and tried again to no avail. I don't know if the PTC login requires a different API. Please let us know how to fix it!

**Comment by brianguy1** [comment]
I figured out the answer based on Xrecon420's post on another thread. The PTC account is considered a new account so I needed to login and capture my first pokemon. After that it allowed me to start scanning. It won't allow me to move my marker now but at least the first issue was cleared up. 

Thanks for the great community support and hard work on this project.

**Comment by Isterius** [comment]
@brianguy1 just turn off option Location Settings -> Scan follows location :)

**Comment by lairmongomap1** [comment]
Same here created new account, but it says possible ban location settings turned of and first pokemon captured

**Comment by himeshpatel88** [comment]
I have created a new PTC account, logged in on my phone, caught my first starter and then logged into the app, it will scan for about 10-15mins before showing status as "Possible Ban", I then have to close all windows and re-open for it to continue to the have the same problem, is there a way around this?

**Comment by Isterius** [comment]
try catching some pokemon after creating your account, than it'll work :)

**Comment by askeland** [comment]
Guys, remember to activate your accounts. The "possible ban" appears if not :)
