### ISSUE TITLE
Important

### ISSUE THREAD

**Issue by furax187** [mchristopher/PokemonGo-DesktopMap#1030]
I got banned today and I only sniped 1 time ( using pokesnipers ) to catch 5 pokemons. I used everyday the pokemon go map with a fake login. Now I'm wondering did any1 got banned already for using ONLY a tracker app/ pokemon go map? So NO BOTTING,SNIPING,ONLY USING tracker apps/pokemon go map?

**Comment by NickIxo** [comment]
Yeah i have plenty of accounts that have been banned using only this program. but as others have said, just make more and move on.

**Comment by galaxy9999** [comment]
You scan and you will be banned. So it is the new norm.

**Comment by jecates** [comment]
I used only this app, and all my accounts I've logged into using this app have now been banned.

**Comment by furax187** [comment]
@jecates

do you mean that the account you've played with is banned? or do you mean the fake account you use to login into pokemon go map got banned?
Because its a huge difference. Cause thats what i am trying to figure out.

**Comment by anon2019** [comment]
been using this for a while now and using a burner PTC account exclusively for this and it got banned 4 days ago

**Comment by furax187** [comment]
@anon2019 and your account that you play on your phone is still in good standing? If thats the case, they only ban the account which you use to login into the pokemon go map.

**Comment by anon2019** [comment]
Correct. The PTC account that i use the play the game with on my iPAD is still in good standing. I use this app and the game on the same networks (home/work/mobile). I submitted a claim that it was terminated in error  just for fun.

**Comment by jecates** [comment]
@furax187 I had a couple PTC accounts that I used on for this map, but I also had previously used this map using my actual account I played on. All of them were banned. 

I never did anything other than use a map (no sniping or auto catching or anything like that), but I did also use a third party app (Blossom's Pogo Manager) for checking IV. 

There's no relationship between my PTC accounts and my "play" account, so I'm sure my "play" account was banned for using the map and/or using the pogo manager. Both are bannable offenses, and easily detected by Niantic.

I had fun playing the game while it lasted. Was 8 away from my complete North American pokedex, so I wish I'd made it another week or so to finish, but oh well. I said this many times over the past month, and it holds true even after getting banned - I'd much rather play the game the way I want to (rushing to go catch a rare pokemon, spending tons of time trying to find nests, etc) and then get banned for it, than "play by the rules", walking around aimlessly hoping to randomly stumble upon something I needed for my pokedex, and not get banned. I had fun playing the game for 6 weeks, and it's kind of a relief to not be tied to it so much anymore (I was ready to quit as soon as I completed my dex, anyway). That seems better than not having fun playing for as long as I want (which probably would've been less than 6 weeks, tbh, because it became boring catching the same ol' junk near my house and work after about 2 weeks).

**Comment by pill0ws** [comment]
@jecates 

Man it sucks hearing that. I have pretty much stopped using the map tracker but I used it enough that I could be in line for a ban for all I know. They have banned 2 of my burner accounts, I made a 3rd one today and it seems like it wont login via game client or the new App although it logged in via the old version of this app. I pretty much started using the App as a gameplay mechanic, keeping it on follow mode or toggling it off completely and using it only every now and then to scan small areas. To this extent it really did improve the gameplay as it felt like sending out one of your own pokemon to search an area. i would love for something like that to exist in the game but they want to call it cheating. People train dogs to fight and they train dogs to hunt, the developers of this game would rather you have fighters than hunters. I'm going to lay off the new burner and the new version of the App although I really wanted to log all the spawn points I could before giving it up entirely. However I'd rather not risk it and it may already be too late. meh, I've dropped at least $100 on this game since launch and if this account gets hammered, I'm either done entirely or I will just go full force cheat mode with new accounts just because fuck it. My main account is about as legit as you can get, over half the population used pokevision when it was up for a reason, not just because the tracker was broken but because it complemented the game in a manner that involved using google maps with a game designed around google maps. The new tracker still has you walking in circles but I have had a lot of success with it, its just annoying as fuck that it shows grass underlying pokemon that are on the road or in the water or in wetland, etc. The new Appraisal feature is also not nearly as cool as a legit IV checker and honestly thats neither scanning or botting, so hopefully they dont ban me for that. Damned grinches! Maybe their shoes are too small
