### ISSUE TITLE
Non-techie needs help with setup

### ISSUE THREAD

**Issue by chrismartingo** [mchristopher/PokemonGo-DesktopMap#1057]
So, I am not a code guy.  I know as much about computers as the average person.  The tracker works fairly well for me, but it only goes about 1/4 mile out from my house and it is slow to reload.  I see people with screen shots of huge areas covered and tons of search circles overlapping.  I would appreciate some help in setting up to cover a larger area with faster searches.

I have a MacBook Pro and the only thing I have installed is the OS X zip file for version 3.2, which I am currently running.  Should I be installing or running something else to get the results I see other people getting?

Thanks for your time.

**Comment by Arsar01** [comment]
Same issue here, except running windows 8. Commenting to follow thread

**Comment by Edcwae1a** [comment]
I can't get this to work on my MAC any more. It used to work. The account I was using got banned. I've made a new account, and it is not banned. (I can play the account and have) But the when I run the OS X version 0.3.2 it just says OUTAGE and then POSSIBLE BAN. 

I've made a new API Key.

What I am wondering is do the API Keys, because they are associated with a Google account - is it possible if there ever was a PTC account that was banned using an API with that google account mean you can no longer use any API with that google account. If that makes any sense. Basically do I need to make an API key with a different google account because I know I had a PTC account that was banned with using an API key with that google account. Even though I never logged in with google in the map??

Anyone else have problems running the new map on OS X?
