### ISSUE TITLE
No Google login available only PTC and possible ban + other errors on download

### ISSUE THREAD

**Issue by peachpunch78** [mchristopher/PokemonGo-DesktopMap#1058]
I cannot login with google it only gives me the choice to login with pokemon trainer club. When I open the map it says waiting then goes to possible ban where it normally says operational. And when I downloaded the new update an error message popped up.

**Comment by pill0ws** [comment]
I've had tons of issues with the new release. Ultimately boiling down to problems with the PTC servers. I made a new account and cant even login with the game because it says the password is wrong, however I can login to the website. My older account gets the same error although it may of been banned. I know my original PTC account was banned for sure as  Ichecked the email but the last PTC account I had been very conservative with and rarely ever even toggled it on anyways but just hate walking in circles looking for something. I feel like aimless walking is bad design, Niantic may praise walking aimlessly but I like to aim where I am going, I like to know where my destination is and why its my destination. The map app provided that but it sees some more Niantic crap is looming in the background because if the game client itself wont let a new account login via the PTC servers then something is wrong. I don't think its the app, I think some more changes are coming, eventually they will work their way down the list of 3rd party apps they hate to map scanners, theyve gotten pretty good at dealing with some bots and some exploits so my guess is we're next on the list. They want us walking in circles staring at our phones, not reading street signs and hauling ass to a distant location because we know a Snorlax is there
