### ISSUE TITLE
feature request: Display spawn point type. 

### ISSUE THREAD

**Issue by galaxy9999** [mchristopher/PokemonGo-DesktopMap#1080]
According to the reddit post: https://www.reddit.com/r/pokemongodev/comments/4yzqc2/spawn_point_types_clearing_confusion/ There are 6 different spawn point type. It will greatly improve the prediction of when next pokemon will spawn and whether a same one will spawn in 15 mins (2x15 type). 

Thank you!

**Comment by qmech7k** [comment]
Does anyone know how this scanner treats non 15-min spawns? 

I modified the scanner a while back (can't get the recent version to compile on Linux, though) to also include the time of the scan (detect_time). Looking at my data, I have 3715 spawns scanned after adding the detect_time. Looking at the difference between disappear_time and detect_time yields 3684 between 0 and 15 minutes. 7 are MUCH larger (29 to 32 THOUSAND minutes), while 24 are massively in the negative (same order of magnitude as the huge positives, just opposite sign).

**Comment by qmech7k** [comment]
Okay, so I've looked at my data in more detail and the scanner itself. Because of the way the database works, the scanner NEVER records duplicate encounter_id's. The result is that the only way to detect if a spawnpoint is one of the oddball ones is to have lots of data and look at the results. Including detect_time helps analyze the data, but just looking at the disappear_time is enough.

To see if you have detected any oddball spawnpoints, run the following query on your database:

SELECT spawnpoint_id,COUNT(spawnpoint_id) AS c FROM (SELECT DISTINCT  spawnpoint_id, strftime("%M",disappear_time) FROM pokemon) GROUP BY spawnpoint_id HAVING c > 1

This query returns any spawnpoints with multiple different disappear_time minutes-past-the-hour.

To determine what kind of addball spawnpoint you have requires A LOT of data and detect_time (which isn't recorded by default) or some manual scanning. If you have a lot of randomly sampled data points from the same spawnpoint, looking at detect_time will tell you when there is a pokemon, even if disappear_time is invalid. For example, if all you detections fall between xx:02 and xx:32, then you clearly have a 1x30 spawn. If there is a single 15 min gap, then you have a 1x45 or 1x60h3, where looking at where the valid disappear_times fall will tell you which one. And so on.
