### ISSUE TITLE
[Request] Select certain areas NOT to be scanned.

### ISSUE THREAD

**Issue by HighOnTacos** [mchristopher/PokemonGo-DesktopMap#1096]
My neighborhood is a bit oddly shaped... There's a 2x3 section of blocks, across the street from a large open pasture, In that open pasture, there is not a single pokemon spawn. Then, at the west end of my neighborhood, is another 2x3, vertically, creating somewhat of an L shape. If I set the scan radius large enough to get both sections of the neighborhood, it takes 20+ minutes to scan the whole area, spending 10 minutes of that time scanning the empty area. 

It would be a huge help if I could just block out that area, and have it resume it's scan pattern on the other side.

**Comment by dhyde79** [comment]
I somewhat agree with this, I'd personally love to have the ability to set scan patterns, instead of it always being a circle...additionally, a "start/stop scanning" button would be amazing...that way it doesn't start scanning then I pop in via mobile and its area of scanning suddenly jumps from my house to wherever I'm at on mobile and had something pop up on my nearby that I want to find...

**Comment by HighOnTacos** [comment]
The area that the mobile website sets to is the last area set from your
computer, even if you've moved the marker on mobile. I hadn't even thought
about that - It needs to be fixed.
