### ISSUE TITLE
0.3.3 still has  the DEADLY JavaScript error and auto update somehow destroyed 0.2.1

### ISSUE THREAD

**Issue by galaxy9999** [mchristopher/PokemonGo-DesktopMap#1099]
The 0.3.3 still have the same JavaScript error on all even windows in multi-window situation (described it her https://github.com/mchristopher/PokemonGo-DesktopMap/issues/1035) and now I can't use 0.2.1 which did not have JavaScript error after the new update. How do I make 0.2.1 work again? My 0.2.1 has Java error. :/

**Comment by ndsvw** [comment]
0.3.3 does not work because nothing has really changed in comparison with 0.3.2

**Comment by galaxy9999** [comment]
Can dev or any expert here please please help with the JavaScript error so that many of us can finally enjoy the latest version after 0.2.1?  JavaScript error can occur with 0.2.1 as well. However, it can be fixed by deleting C:\Users[username]\AppData\Roaming\pokemon-go-map and the file pogom.db and the folders Cache,  However, this fix does NOT work on any version after 0.2.1. 

Thank you very much!

**Comment by tangrl** [comment]
Beloved version 0.2.1 stopped working this morning and couldn't make 0.3.3 working. When running in Server mode, 0.2.1 works all day long even recovers itself after internet service being down. The newer version just displays "Possible Ban" and stops working. Since it's Server mode and I'm away, it can't be recovered.

Wish we can restore 0.2.1.

Thanks!
