### ISSUE TITLE
new release 0.3.3-Possible Ban

### ISSUE THREAD

**Issue by MelW1978** [mchristopher/PokemonGo-DesktopMap#1103]
Possible Ban still appearing with new release :( 
Can someone tell me how to fix this or sign in with Google Account where I have no problems,
Ive tried two different accounts with same issue

**Comment by ndsvw** [comment]
same problem.
Between 0.3.2 and 0.3.3, nearly nothing relevant has been changed:
https://github.com/mchristopher/PokemonGo-DesktopMap/commit/a81426a3d9cb45e020d6c744f56b1084d6404f69

**Comment by youtubesteak** [comment]
Your account is probably banned. Logging into a google account with the current API results in instaban, so it was removed. Try creating a new PTC account, go through the tutorial on the phone app, then try to log in. Accounts seem to be banned about every 2-5 days after using the API, so you will just need to keep creating new accounts.

**Comment by galaxy9999** [comment]
I am so curious that you do not have javaScript error when running more than 1 window?

**Comment by MelW1978** [comment]
Logged into PTC with Phone and worked fine. still saying possible ban and this is the third account created?!? :(

**Comment by youtubesteak** [comment]
Strange, possibly firewall blocking the program?

**Comment by youtubesteak** [comment]
@galaxy9999 I do. I've had the same issue for many releases, since maybe 0.1.1 or something. But normally, I just use a spreadsheet to manage accounts and scan locations. The javascript error seems to not affect the scan location if I don't move the location marker, so I just ignore it. I've tried logging out and back in until there isn't an error, and it shows the correct location, but since it doesn't really affect the scan location, I typically just ignore it instead of wasting my time doing that.

**Comment by galaxy9999** [comment]
Interesting, my JavaScript error definitely affect the scan location on all even # of the windows I opened. :/

**Comment by youtubesteak** [comment]
@galaxy9999 Are you sure it does? Mine will show the marker at the wrong place, typically the location of the previous login window, but the actual scan location is correct. Try turning on scan locations on the first window opened, and for each additional instance, even if it is showing the wrong location, don't move it, and see in the first window if it is actually scanning the correct location.
