### ISSUE TITLE
Why are all the issues closed?

### ISSUE THREAD

**Issue by vincentcox** [mchristopher/PokemonGo-DesktopMap#1129]

**Comment by torantal** [comment]
Probably because the majority weren't issues, but feature and help requests and this is where actuallsoftware issues should be reported.

**Comment by nakratz** [comment]
Most likely because this Git Repository is just a wrapper around the project PokemonGo-Map which is where most of these features are being implemented. So when mchristopher releases a new version its mainly pulling the latest branch from that project. 

https://github.com/PokemonGoMap/PokemonGo-Map/

**Comment by romanticheart** [comment]
@torantal Is there a good place to go for help requests?

**Comment by AVellucci** [comment]
Issues were closed as most were stale issues that were probably resolved in newer versions, others were just suggestions that have been noted. but the majority of "valid" issues were for the Map project and not for this project.
