### ISSUE TITLE
Scan only happens once, then stops after the first onceover (and is terribly inefficient)

### ISSUE THREAD

**Issue by ghost** [mchristopher/PokemonGo-DesktopMap#1143]
Like title. 
I have a radius of 7 patrolled by 12 accounts, but instead of cycling through it, once they're done going through the radius once, they just stop, and the app needs to be restarted manually to make the scan restart from the center.

Also, the scanning pattern seems to be absurdly inefficient, with no option to ignore spawnless areas, and with scanned areas often being scanned more than once.

In practice, whereas the three accounts should be three times as fast as a single one, it actually ends up being barely one time and a half faster.

Although the main problem remains that the scan doesn't cycle and just ends after one runthrough.

EDIT: Deleting the Appdata pogo folder or rebooting didn't do anything

**Comment by dripsin** [comment]
The program still has it quirks. More accounts gives you more coverage and a little more speed but its not gonna be a direct 3x times faster. There is more variables in play.

**Comment by IonJam** [comment]
That's just a pet peeve.
The real issue is that after scanning ONCE it stops doing so.
It's an app-breaking issue.

**Comment by Jeretron** [comment]
Same problem here, the problem started since patch 0.2.1 for me when there was no account merge so this is longer time problem for me.

- Scanning starts to slow down after one full hexagon scan, circles starts to turn from green to yellow->red->gone (less and less pokemons are picked up after the color changes)
- Accounts are still working as "operational" even tho they are not scanning anything
- Re logging accounts makes them function normally again for a while until the problem starts again
- The size of the hexagon or the amount of accounts that are linked to scanning does not make difference really, the scanning slowdown always starts happening anyway.
- I'm using 11 PTC accounts, and even with different hexagon sizes, the results are always the same. 
-Scanning used the work as long as the app was turned on before this bug started happening (no, these accounts are not banned) 

I have found out that using scanning  in a less Pokemon dense area doesn't cause scanning slowdown, I wonder has the problem something to do with the amounts of spawn points there is for pokemons. (If I recall right the problem started for me when patch notes introduced these spawn point markers but I'm not sure.)

http://imgur.com/8X25YSP
http://imgur.com/p2ZQbL1
http://imgur.com/foqH9Uk
This is what is going on. I started taking pictures when the slowdown started, all of the accounts were working normally and being bright green at the start (pictures are from 0.3.3 but the problem is same even with one big scan in 0.3.4). 
0.3.3 The accounts always start to slowdown in random amount of time and also which accounts slowed down was random also (around 80% of the accounts stopped working in 15min to 2h period)
Now in 0.3.4 the one big scan always slows down after one full scan and slowly stops scanning completely and reboot is required.

**Comment by IonJam** [comment]
To this I'll add that sometimes logging out and back into an account my make it work again, but it breaks after a couple circles, often before even completing a radius 3 hexagon.

**Comment by luckytom333** [comment]
On one computer, I have the same issue.  It scans great once around, then slowly dies until it completely stops.  I then have to close and reopen the program.  My other computer works fine, it's been running all day.  Uninstalling and rebooting does not help.  Any suggestions?
