### ISSUE TITLE
Please change Scan process

### ISSUE THREAD

**Issue by manojrajput** [mchristopher/PokemonGo-DesktopMap#1153]
Hi christopher, could you please make the change in scanning process and make it like old scanning pattern that scan should start from placed point and goes all the way around. Please ....

As if i wants to scan a big area like 50 + then what happens the scanning process scan half portion of where point was placed instead of going round and round in all directions.

Please please...help...

**Comment by Rayenous** [comment]
I believe the current scan pattern is a design flaw.  A common use for program is to allow it to regularly scan an area, but be able to move the pin around to quickly scan certain areas.

With the current scan pattern, the pin is useless, as you have to wait for the full large scan area to complete instead of simply scanning the small area you want.

Example:  I regularly have my scan radius set to 4.  I scan the area around my work/home (wherever I am).  -  When I want to scan the Mall nearby, I move the pin, let it scan for a radius of 2, and move the pine back... now I have to wait for a full scan radius of 4 to complete at the Mall to be able to scan the small are I wanted. - Alternatively, I have to log out and log back in every time I want to scan a small area, so that I can change the scan radius.

For many, this change is a very inconvenient design flaw.

Perhaps you could add an option in the login screen or menu for various scan patterns?

**Comment by mchristopher** [comment]
The scan pattern is part of the map app. I won't be changing it or reverting it, but feel free to ask in the map project: https://github.com/PokemonGoMap/PokemonGo-Map.
