### ISSUE TITLE
Recover from loss of Internet connection

### ISSUE THREAD

**Issue by tangrl** [mchristopher/PokemonGo-DesktopMap#1166]
Every time when my home Internet service experiences some downtime and comes back, Pokemon Go Map displays "Possible Ban" and stops scanning. It's very annoying that I'll have to restart all the instances. Especially in Server mode, I'm away with my mobile device and have to come home to restart it.

When version 0.2.1, it would recover itself. Can we do the same thing?

Thanks!

**Comment by tangrl** [comment]
Just notice that it sleeps for two hours before tries to recover. Can we make it shorter, or configurable?

**Comment by sterlingrpi** [comment]
I have the same problem when loosing internet connection. Whenever I find it on "possible ban" status I see that the last pokemon were only about 1 hour ago. I restart the scanner and everything is fine. It is nice to hear that the scanner recovers after awhile. I guess that's why I never have an interruption that is longer than an hour or two.Would be nice if it could try to recover more frequently.  I guess I will try to work on making my wifi connection more stable.
