### ISSUE TITLE
Couple Bugs

### ISSUE THREAD

**Issue by cooler67** [mchristopher/PokemonGo-DesktopMap#1167]
I think i've come across a bug that only affects Snorlax. The bug was a reporting glitch. It says there was a Snorlax nearby and there was. I went out to catch it, came back home and it expired. Then about a minute later, the alert goes off again. It's claiming Snorlax had spawned again in the same spot. I thought, there is no way. So I went to check out and sure enough it was not there. When I went back home, I found the map only recorded the false second spawn and not the actual spawn itself. Basically, it was saying it only spawned the one time, and never recorded the actual time it spawned the first time. Both Screenshots are from the same day and hour. 

![this happned](https://cloud.githubusercontent.com/assets/21001979/18232644/5b20ed8a-72a2-11e6-9c85-441d842486a3.png)
![odd bug](https://cloud.githubusercontent.com/assets/21001979/18232646/5f9cbf10-72a2-11e6-8deb-aa928d234466.png)

**Comment by jareem** [comment]
Longer spawn time ?

**Comment by tengski** [comment]
happend to me too. the senario was. a snorlax appears with a 2mins time remaining. I was plannng to go but I will not make it on time. so i stayed. i rescan that part of the area. and by that time snorlax was goin to disappear in a few seconds. and it does after 3-5 seconds a 2nd snorlax again appeared on that same spot where the first snorlax appeared. i went there and i got it.   ill try to provide some screen shots but the data is all gone.

**Comment by blahblah3141** [comment]
It is the same Pokemon, and, in fact, the map itself knows its the same Pokemon. It is due to the fact that the Snorlax may have a timer greater than 15 minutes (e.g. 30 minutes) but the scanner, due to some fundamental limitation with respect to scanning, cannot detect this. Instead, it reappears again as a "second" Pokemon after 15 minutes.

To confirm that this is the case, and not a "freak double-spawn", if this happens again, simply go into full stats mode and look at the Pokemon spawns for the last few hours, and you will see that the Snorlax (or whatever else) has only been marked as having spawned once.

If this answered your question, please close this issue as the issues page is already getting too cluttered with questions like these.
