### ISSUE TITLE
Use only a server

### ISSUE THREAD

**Issue by iCiccio25** [mchristopher/PokemonGo-DesktopMap#1207]
There is a way to use the same server also when i close and re open the app?

**Comment by Acaceres1996** [comment]
Are you talking about the same ngrok.io URL?

What i did to solve that is to download ngrok myself and keep the same instance running since day 1. As long as you dont close the ngrok interface, everything in your localhost will be transmited to the url. 

Basically, by using ngrok yourself, you can choose when to close the server. The app closes the server when you logout or when the app closes down.

**Comment by iCiccio25** [comment]
Ah understand. Is there a guide to follow? I'm a noob eh eh

**Comment by AnarkhiA** [comment]
or, just turn on server mode & connect to your ip:8000 that case you're not limited by the stupid 20 connection/min limit.

**Comment by Acaceres1996** [comment]
The problem with that solution is that it is not so simple to configure your machine to be seen on the internet.  if you are in a network of computers working with the same public IP (Which is the most common case), then you will need to make some forwarding on the router side.

It is a plausible option, but I think ngrok wins in usability (And not everyone knows how to do the former)

**Comment by AnarkhiA** [comment]
i agree with you to an extend. If you cannot forward a port because of permissions, ok, but everybody can google how to. Its alot more stable in my opinion
