### ISSUE TITLE
outage

### ISSUE THREAD

**Issue by arn3** [mchristopher/PokemonGo-DesktopMap#121]
hello, i donwloaded this app yesterday and i was really shocked how good it was! so props to the makers of this. But since today when i openened it and signed in, no pokemons appeared. Also something that wasn't before was that there is a red text above the map with "outage" what does this mean? And how can i fix this?

**Comment by arn3** [comment]
oops pressed by accident on enter xd. 

was that there is a red text above the map with "outage" what does this mean? And how can i fix this?

**Comment by joshuacane** [comment]
I made an account just to respond to you haha. Apparently the app is suffering an outage due to the fact that Pokémon Go went live in Japan. The servers are being overloaded once again and without the servers, the app won't work at all, hence the outage. Pokémon Go is working sporadically and so is the app, so that means the app is still very much functional.

**Comment by arn3** [comment]
oooh alright, thanks for the response!

**Comment by ranrinc** [comment]
The Server got hit very bad... so expect offline this weekend...
