### ISSUE TITLE
Scan once and then stops

### ISSUE THREAD

**Issue by srenobdrawkwa** [mchristopher/PokemonGo-DesktopMap#1213]
I setup 55 accounts with a radius of 14 with in The last 24 hours when I start the server it seems to scan fully once and then doesn't scan again and I have to exit and restart server. Anyone had the same problem when starting and know how to fix this?, cheers

**Comment by tleple** [comment]
I have the same problem here.

**Comment by secondhandnudes** [comment]
Same issue. I had to downgrade to the previous version because regardless how many accounts I tried to run, or what radius I set, this always happened.

**Comment by srenobdrawkwa** [comment]
Can I downgrade without having to readd all the accounts 😕

**Comment by srenobdrawkwa** [comment]
And are you using windows10?

**Comment by tleple** [comment]
I think the issue is related to the accounts number, because I decreased its value and the program started to scam periodically again.

**Comment by tleple** [comment]
I'm using Windows 7.

**Comment by srenobdrawkwa** [comment]
How many accounts you running?

**Comment by secondhandnudes** [comment]
Yes I'm on Windows 10. And once you downgrade, there's no multi-account support anymore, so you can't even re-add them. I just reverted to my old method of having 3 instances running with 1 account each, which isn't perfect but at least it works. 

I don't believe it has anything to do with number of accounts, because I tried running that version with only 2 accounts and it still had the same issue.

**Comment by tleple** [comment]
The perfect number for me is 12 accounts scanning 13 radius regions
