### ISSUE TITLE
Any way to send push notifications to a mobile device?

### ISSUE THREAD

**Issue by tinarazzburton** [mchristopher/PokemonGo-DesktopMap#1218]
it would be nice if there was an easy way to have the desktop app send a push notification to your mobile device when something on your notify list appeared.

**Comment by DHollande** [comment]
That'd be the ideal feature - something that could directly push notifications either to mobile or via email or SMS as the notifications pushed out by the 'Share Mobile' are a bit flaky.

**Comment by PJRay** [comment]
Maybe using PushBullet or similar?

**Comment by homerfan123** [comment]
In the issue #869 there was already a discussion and solution but no further steps.

**Comment by DHollande** [comment]
> Maybe using PushBullet or similar?

I see some mention of Poke Alert being capable of sending notifications from this version, but the specifics on implementing it are slim.

**Comment by baer1** [comment]
today i was able to get push notifications on my phone. unfortunately its a standalone solution for myself so i cant publish it.

the idea was to use the IFTTT Maker channel to get Notifications to the smartphone 
#https://github.com/mchristopher/PokemonGo-DesktopMap/issues/1165

the map has already the ability to set up a webhook with some limitations.
1) the problem is that the webhook does really send everything. so you cant set
the maker channel url directly in the config.ini of the map. you wont be happy because
you would get flooded with messages.

so i was developing my own small webservice for the webhook and filter the events there. 
i am basically  repacking the post i am getting from the pokemon go map and do a maker channel post there. (but only the events i would like to know)

the second problem is that the webhook doesnt get called when you have already set a notification in the desktop version. so i had to remove the notifications in the desktop map.

the best solution would be a integration of the ifttt maker channel in the desktop map
under the notification settings.

**Comment by androidfan84** [comment]
I made a request in #869 for the tutorial.

**Comment by homerfan123** [comment]
better than a training would be a direct implementation in the application @mchristopher :)

**Comment by baer1** [comment]
unfortunately i have had to find out that the webhooks stop after a while and my data layer application is not called. but i am working on something new

**Comment by tinarazzburton** [comment]
There was this other project that had a method for sending notifications for Push Bullet... i know nothing about coding, but maybe that would help in figuring out an integration?  https://github.com/jxmorris12/PokemonGo-Finder

**Comment by squirterbulb** [comment]
I get notifications on my phone. I didn't have to do anything

**Comment by ehsians** [comment]
Right now, what seems to be working for a bit is using the default samsung phone internet browser and loading the map on that. Setup the Very Rare, Ultrarare notifications, set sound. When you close the browser, it sends Notification alerts on the phone.

**Comment by random189268** [comment]
PokeAlarm works, you just need to edit the config for the map to enable webhooks then give that IP and port to PokeAlarm so it knows where to monitor for spawn data.

More info/brief tutorial in the issue I opened a few weeks back:
#1191

**Comment by tinarazzburton** [comment]
Do some people already get push notifications?  I open the ngrok link on my iPhone with Safari and it never sends any kind of notification.  If I'm actively looking at the map I can see the rares bouncing up and down, but it never shows any kind of alert.

**Comment by tinarazzburton** [comment]
Thanks for the comment about pokealarm, but I didn't see much of a tutorial.  I'm not even sure how to install pokealarm
