### ISSUE TITLE
Error: Cannot call loadURL because the webContents is unavailable. The WebView must be attached to the DOM and the dom-ready event emitted before this method can be called.(…)

### ISSUE THREAD

**Issue by Showmanxzzz** [mchristopher/PokemonGo-DesktopMap#122]
Hello. I run Pokemon GO Live Map.exe, insert your data, then the map is loaded, but the Pokemon do not appear on it. Please tell me the reason may be what?
http://prntscr.com/bw3xr9

**Comment by fangwei007** [comment]
Hello, I got the same issue, it happens after you run the app for a while when pokemons start to disappear and never shows up again

**Comment by koliha** [comment]
This is related to this issue #72 and has already been addressed (changes have been committed).  Fix should be present in release 0.0.8 (not released yet, hopefully soon?).

**Comment by Showmanxzzz** [comment]
Error: Cannot call loadURL because the webContents is unavailable. The WebView must be attached to the DOM and the dom-ready event emitted before this method can be called.(…)

Please, tell me, how to fix this error?

**Comment by Pineyka** [comment]
My English is poor. I'm sorry but I can bring something to the project.
I had still problems with the desktop maps.
Error: Can not call loadURL because the webContents is unavailable
White screen, disappearing Pokemon, the problem with the location, login failures and errors.

The reason for this state was installed earlier Python27 and entries in the environment variables
https://hajloo.files.wordpress.com/2011/07/python_path.png

I installed earlier Python25 then Python 3.x and yet Python27
She made a mess there.

PokemonGo-DesktopMap run from a different directory, and the path to the file python was bad. She directed my previous installations and there looking for libraries.

After uninstalling all versions of Python and removing entries from the environment variables PokemonGo-DesktopMap began to work properly. Everything works beautifully instantly.

If you are not a programmer, and you tried to play python PokemonGo Map and recommend to remove plants and to rely only on what you have in the folder PokemonGo-DesktopMap. There is everything you need.

It works on my versions of Windows 8 / 8.1 Windows 7 and Windows 10 without problems
Regards.

**Comment by Showmanxzzz** [comment]
Delete Python, delete environment variables. 
Now http://prntscr.com/bwahcw and white screen
Help me please

**Comment by sfarfals2** [comment]
I had a problem with my account name, maybe u have it too..try copy the app folder to the disk directory (C:\\), and run it
