### ISSUE TITLE
blank scan

### ISSUE THREAD

**Issue by memosoto** [mchristopher/PokemonGo-DesktopMap#1224]
I'm scanning different areas in my city but the scan comes up blank, but i know for fact that there are Pokémon cause im watching them on my mobile. What's wrong?

**Comment by Acaceres1996** [comment]
Im having the same problem in the last 24 hours (My scan has been running for 48 hours). Are you using PTC accounts?

In my case, i have already identified it is an IP ban problem. I don't know about yours (If you have access to your network configurations, you could try to renew it in order to test)
