### ISSUE TITLE
What's the Max accounts and biggest radius possible?

### ISSUE THREAD

**Issue by srenobdrawkwa** [mchristopher/PokemonGo-DesktopMap#1233]
I added 55 accounts and jumped it to R15. Scanner never worked. I'm pretty sure I got an IP ban straight up. Wondering what's the most accounts and biggest radius someone has achieved and still had a functional scanner.

**Comment by srenobdrawkwa** [comment]
Got it working at 15 accounts R7 and this time I'm going to attempt to build it up slowly by adding 3-5 accounts daily and increase radius every 10 extra accounts i make.. Hopefully I can get it to a travel radius of 15 minutes in all directions and 3-4 minute full scan 😄

**Comment by st0nec0ld** [comment]
how i add more ptc's accounts?

**Comment by tntckoo** [comment]
i working on super scanner, now working with r30, 50ptc, working good 2 weeks.

**Comment by cpbeckner** [comment]
If I could make a suggestion, I did have several of my accounts get banned.  In replacing those accounts, I logged into them thru the app.  After catching the stater mon, I also caught another mon.  Since then, those accounts were not banned.  I also created some other accounts but did not take this extra step of catching an additional pokemon.  Give it a try if you are getting bans.

**Comment by KevinTea** [comment]
Hi I have working 50 PTC in range 13 and seems to work well at first, the issue comes when the second scan or attempt begins to put more accounts or rank as the trail gradually lost, holes appear in the scan and loses speed when it should be the opposite. I have 4 GB of RAM and Windows 10 for if you ask, and I would like to know what is prohibited. :D Saludos desde Argentina- Mar del Plata
