### ISSUE TITLE
Scanning but not finding anything

### ISSUE THREAD

**Issue by bmyers72** [mchristopher/PokemonGo-DesktopMap#1291]
I have been using this scanner since early august, and of last night at work the app scans but not finding pokemon.  This happened a while back Niantic broke it after an update, and hoping its not the same problem again.

**Comment by seamusbrennan** [comment]
Niantic now requires you to complete a captcha on the account that you use for scanning, which is a pain.  But as of recently, even after completing the captcha pokemon still wont appear for me.  Im really starting to loose interest in this game, I hope this problem will be solve sooner rather than later.

**Comment by bmyers72** [comment]
ahhh that makes sense now thanks thought I was missing something as I use the scanner almost daily.  Yeah without this and the number of pokemon I have 126 I need this to focus my searches.  How do you complete the captcha?  I am not seeing anything.

**Comment by bmyers72** [comment]
never mind I figured it out now.. thanks for the information though.. Yeah fix that garbage!

**Comment by bmyers72** [comment]
yep just did the captcha and still nothing

**Comment by harrison0550** [comment]
According to fastpokemap twitter account Niantic just did yet another security update. Not even completing the captcha will fix your workers this time. Looks like we are up a creek for now.

**Comment by tinarazzburton** [comment]
Welp, Pokemon Go is basically dead now.  It was a nice run.

**Comment by pehmolelu** [comment]
So how did you complete captcha ?

**Comment by HollyKohai** [comment]
https://www.youtube.com/watch?v=WqnXp6Saa8Y

**Comment by AerosHawk** [comment]
I created new accounts and within a day they required captcha. Really lame.

**Comment by Burbankian** [comment]
don't bother anymore, it's not the captcha, it looks like niantic has disabled 0.35 across the board

**Comment by bmyers72** [comment]
Yeah without the scanners this game is going down.  Was a good run and was looking forward to future updates, but whats the point without knowing anything.

**Comment by gismo1901** [comment]
Yepp, can confirm discussed behaviour for heart of europe as well since 2 days now. Additionally, I got a nice msg in black with red letters which tells me that ... we have received a signal, which intends that you are using 3rd party software to cheat ... bla bla ... we strongly recommend you to switch it off ... after hitting the "confirm" button I was able to play as usual. Anybody who experiences that as well?

**Comment by Goof-Troop** [comment]
Since the boom of pokevision ive been playing without a map, until recently (i found this). Id been doing pretty good without one. I know where most of the spawn points are anyway when i go for a walk most of yous should too. Only now i dont know whats out there, so the mystery returns. for me, map or no map ill still be going on my hunts.

**Comment by AbrahamBlinkin1** [comment]
The people that enjoy walking around blindly looking for Pokeman... I simply don't understand you. At all. There is absolutely **ZERO** "mystery" in taking a walk, seeing something that you don't have pop up on the "nearby" radar, and then having **ABSOLUTELY NO REALISTIC HOPE** of finding it.

None.

Without any form of a scanner, this game is dead. Sadly some people will continue to limp through the process, so until the players abandon the game in droves (see: millions) Niantic also has **ZERO** interest in ever fixing their on-board scanner, and instead will spend their programming efforts in adding more crap nobody wants, nor needs.

Stick it in your long grass, Niantic! You're a bunch of digital fascists.

**Comment by HollyKohai** [comment]
It's getting cold out. There's clowns in the streets at night. I'm not walking outside of my house anymore without an actual method of playing and enjoying the game.

**Comment by taylormeyer** [comment]
too funny @HollyKohai. does anyone know if there are any efforts being made to try and get around the latest blocks? unfortunately without this application the game is not much fun to play
