### ISSUE TITLE
Default Sound notification

### ISSUE THREAD

**Issue by Calvinthesneak** [mchristopher/PokemonGo-DesktopMap#1301]
Curious if the default sound the app plays has changed.

Currently I was changing the file "ding.mp3" in 
C:\Users\LocalUser\AppData\Local\pokemon\app-0.4.1\resources\app\map\static\sounds\

I'm running windows 10, 64bit.  It worked with the previous generation 3.x versions when I replaced the MP3 file.

**Comment by centilian9** [comment]
I think Windows just play his sounds and ignoring this one. Try to ad some other sound in Win sound settings for "Notifications" to check.

**Comment by Calvinthesneak** [comment]
Sadly you're correct.  the 3.x generation would allow for custom sounds at least on my windows 10 machine.  I'll check on windows 7 but I suspect the same.

**Comment by Evilundeathz** [comment]
On windows 10, I changed the sound file at "C:\Users\LocalUser\AppData\Local\pokemon\app-0.4.1\resources\app\map\static\sounds\" to a custom mp3, renamed it "ding.mp3" and after a restart it worked, make sure you have the notify with sound option turned on otherwise the program wont make a sound, just the windows 10 notification  system.
