### ISSUE TITLE
incorrect disappear time 

### ISSUE THREAD

**Issue by zhenggb72** [mchristopher/PokemonGo-DesktopMap#1312]
It seems every pokemon appears on the map as if it is just spawned at the time when it is found. The  disappear time is always 15 minutes to begin with.

**Comment by harrison0550** [comment]
+1 Noticing the same thing.

**Comment by PhilipposVassil** [comment]
+1 Noticing the same
now some pokemon are 15 some 30 and sometimes cant find pokemon at the pokespawn
in the same hour there are 2 times that pokemon spawn at pokespawn

**Comment by harrison0550** [comment]
I'm hoping this is just due to this event Niantic is running and it goes back to normal after the event. I've ran out the door twice when the alarm for Draganite went off. Got two blocks away where it said it was and instead it was just a huge cluster of random pokemon that weren't on the scanner. I'm running 35 PTC accounts on 12 radius so its refreshing plenty fast enough.

**Comment by stdu00** [comment]
+1, same problem here. Impossible to know if I have the time or not to go the point :-(

**Comment by minim8** [comment]
Niantic changed the algorithm, time is now only sent if the Pokemon despawns in less than 1 minute.. I think this was an anti scanner update from them and one of the multiple reasons why Waryas quit. (no chance of holding the 200m radius if you cant go for spawnpoint scanning anymore)

**Comment by Rayenous** [comment]
It could probably estimate the despawn time based on the last time the location was scanned.... but I guess there is still no way for it to know if it's a 15 or 30 minute spawn timer.
