### ISSUE TITLE
Constant false spawns

### ISSUE THREAD

**Issue by Arthuriing** [mchristopher/PokemonGo-DesktopMap#1326]
Every so often, I scanned false spawns, the pokemon never been there and the livemap shows as "12 minutes reamaning" or so, my point is even pokemons with over 10 minutes left are fake flagged spawns. Anyone else having that? It's not ALL that is false but it's kinda 35% of the spots are false.... that is frustrating me because everytime is a 90%+ IV pokemon xD

**Comment by Calvinthesneak** [comment]
The timer portion is not accurate anymore, since Niantac only sends a time if there is less than 1 minute remaining.  There are 15/30/60 minute spawns, and depending on how long they are visible for before your worker account finds it, it might only have a couple minutes left.

IE I scan an 11 radius with 10 accounts.  It takes my scanners 5 1/2 minutes to complete the loop, so theoretically the timer could tell me 15 minutes left, but really I have less than 10 minutes.

Those sightings are probably not false, but probably despawned by time you get there.

**Comment by Arthuriing** [comment]
Oh, thank you for your answer. =)
