### ISSUE TITLE
Banned after new update

### ISSUE THREAD

**Issue by Ang41187** [mchristopher/PokemonGo-DesktopMap#1350]
I'm not sure if this is a coincidence or not, but the first time I ran the map after the new Pokemon Go update my map account got banned. Anyone else having this problem? Should we refrain from using the map until there's an update?

**Comment by lmnottingham** [comment]
yep, same problem

**Comment by ppianta** [comment]
yeah i created 3 accounts just for using with the map - 1 is banned and the other 2 i have to often login to the pokemon go app with those accounts just to solve the captcha - which is a real pain in the ass btw due to the fact that i can only solve the audio captcha option coz the 'choose an image' option is always half off screen and i can't click the ok button. way to go niantic.

i was kinda hoping the app would be cautious enough not to trigger any ban-worthy behavior.
