### ISSUE TITLE
Will this be updated for Gen 2 

### ISSUE THREAD

**Issue by Ang41187** [mchristopher/PokemonGo-DesktopMap#1359]

**Comment by Ang41187** [comment]
I know it's a long shot, but will anyone be able to update this for Gen 2? My son and I live in a very small town and this was really the only app that worked for is.

**Comment by hachimitsu-ink** [comment]
There might be a chance that the app wont be updated for a very long time but never hurts to check out other alternatives. if you have an iphone I strongly recommend  **PokéTracker** . Downside is that it can only scan about 1-2 block radius while the pro version (within the app $2.99) scans about 3-5 block radious. I also recommend trying Silph road where they give you ideas where the nests are located. If you know these tools, then I apologized.

tip trick::
Naming your eevee **Sakura**   (case sensitive spelling) = Espeon
Naming your eeve **Tamao** (case sensitive spelling) = Umbreon

**_I'm trying Pokesensor, but you need to create fake accounts_** (just incase if one gets banned)
only positive is that it scans only onto sectors, so you may want to type the location region of what pokemon you want to see(example: fishermans wharf, palace of fine arts, City hall etc..)  since it doesn't do the pin drop and it scans within that marginal 3-4 block radius.
(updated: found out it it stated captcha requirement, you may need to go to account settings to redo the capcha in pokesensor)

 while Poketraker, doesn't require fake accounts since it uses a captcha system (ya know, choose how many store fronts it displays, find one with trees etc..)  but if you complete at least 3-4, (it continues on to increase perfromance on scanning but 3-4 is just enough) then just hit the skip button and your ready to go.. 
Downside is it only stays in a fixed location of where you are and you cannot scan another area...

I hope this helps btw since i know the GEN 2 spawn rates are kinda everywhere

**Comment by PhilipposVassil** [comment]
@Ang41187 dont pay for any app!
if you have iPhone check on app store about PokeSensor.
Download it make a fake account to login with and good hunting :)

if you have android download this one from your phone https://github.com/MrPat/PokeSensorAPK/raw/master/pokesensor.apk

The main page of that app is : http://www.pokesensor.org/

**Comment by Rayenous** [comment]
These are all good suggestions for a number of users.  Unfortunately, I have yet to find a good, customizable scanning tool that can be run on a Mac or PC.

This tool has been working perfectly fine since it's last update (captchas happened, but were very manageable... captchas even happen on legit accounts), so it's odd that no one has been working on it at all.  For the most part, it still functions properly, all it needs is to be update with the current pokemon (and moves?).

**Comment by Ang41187** [comment]
@Rayenous you're lucky. I haven't been able to get it to work since December. It sucks because it's the best map I've found for my rural area. I do have Pokesensor on my iPhone but it's not working right now.

**Comment by Rayenous** [comment]
Actually, it stopped working all together few days after my las post.  -  Accounts will no longer even log in.
I am now using globalpokecache (GPC) instead.
The discord channel for it - https://discord.gg/xAaDk
Unfortunately, it's in Alpha, and cannot work withough a token, generated from PokeAlert... which is no longer functioning.
It also requires the user to purchase a Hash Key (from a 3rd party, not the creators of this app), for a few bucks a month.
