### ISSUE TITLE
General feedback

### ISSUE THREAD

**Issue by pill0ws** [mchristopher/PokemonGo-DesktopMap#150]
So I absolutely love the Hide and Notify features. However if you get a massive list going it starts to get clunky. Rather than going for a smaller font though, i think that it could be an even better utilization of space  if the same icons for all the pokemon s where used to populate the list. they are very small and  pretty much tell you immediately what they are by looking at them. Perhaps this is a more advanced feature though and some would prefer full names for the selection process as they may not know what the thing they want looks like. However the display of the notification whitelist and the map blacklist would look a lot cleaner as map resources being as they all have similar sizes. Ultimately associating the name with the icon can be beneficial too

**Comment by tinarazzburton** [comment]
it's awesome being able to set notifications.  I found a dragonite tonight, because it alerted me.  But setting it up is a little cumbersome.  You have to add each name individually each time and scroll through the list.  Being able to pull up a large window with all the names  and simply check the ones you want to notify or hide would be quicker.  If that showed icons as well, it would be even awesomer.  

I've tried using the mobile option, but unfortunately the filters/notifications don't carry over.  I'd have to manually add them all on my phone each time I pulled it up, which would be a little too time consuming.  Also, I don't think notifications work on mobile yet.

**Comment by pill0ws** [comment]
so, another general usability improvement could be from editing the search nodes manually somehow. Currently the search pattern spirals outward and each increase in radius is exponentially longer in distance. So sometimes it is searching over nodes that are inaccessible and would just be a waste of time to scan. Perhaps some kind of "draw" feature to manually scan through areas on the map could make for an interesting "quick search" feature. as well as an "eraser" feature to blacklist search nodes within the selected scan radius that are impossible to reach. The draw feature could be useful when you need to drive somewhere, rather than constantly move the pegs around and scan in spirals, you could just do a quick search of the nodes along that route so maybe if something cool were off to the side not far, you could make a pit stop.
