### ISSUE TITLE
"REQUEST and HELP"

### ISSUE THREAD

**Issue by faataliis** [mchristopher/PokemonGo-DesktopMap#196]
How do i change the location? i mean what do i have to put in? the coordenates? or the adress?
if its the coordenates, provide an example of the order pls
Also, you should add something like just move the red point to change location on map:)

**Comment by misterpink14** [comment]
You do have to enter the coordinates. If you go to google maps and search for a place, the coordinates will be below the little modal when you click on the location in the app. If you click on them, they will be automatically entered into the search bar and you can copy and paste them one by one.

**Comment by kking124** [comment]
Check PR: https://github.com/mchristopher/PokemonGo-DesktopMap/pull/184

I added address geocoding to the login page.

**Comment by pill0ws** [comment]
havng an issue with this, do I past as is? do I remove the comma and leave a whitespace delimiter? I havent had coordinate updates working live yet. Only before longing. I adjusted by running multiple queries but that has some other unique issues.

Would also love if "Use Current Location" could be tied to the mobile device so that upon updating and running a new query, it could be pulled automatically rather than require a logout.

**Comment by misterpink14** [comment]
Everything to the left of the comma you just copy and paste in to the left text box, the same with the right side of the comma. If it's still not working could you send a picture in here. 

I think that is actually in the makings(:

**Comment by pill0ws** [comment]
My issue is with the change location feature once you are already logged in. There is only 1 box for those coordinates. I copy paste from google ut no matter how I format it within the box it does not take. I've tried using a tab for whitespace, a single space, the comma and even no space. I have no problem logging out and changing them via the login location setting.

**Comment by pill0ws** [comment]
<img width="936" alt="capture" src="https://cloud.githubusercontent.com/assets/1319970/17082153/329bba96-5139-11e6-94b7-bd9dae262035.PNG">
