### ISSUE TITLE
[Request] Notification for all Pokemons NOT in "hide common" list

### ISSUE THREAD

**Issue by Kraker01** [mchristopher/PokemonGo-DesktopMap#223]
Is it possible to insert a notification everytime a Pokemon, NOT included in "Hide common" appears on the map?

So it will be easier instead of compiling a new list for notifications

**Comment by Knightrnare** [comment]
Yes, this. Or at least have a save and import option to a local file.

**Comment by pill0ws** [comment]
I see where you are coming from here. Populating that list is very tedius and it becomes harder and harder to see the drop down list until it completely becomes impossible. The same could happen with the blacklist for shown on map icon if someone were very picky about displaying only what they cared about. I think a list preset would be more effective as whitelisting all pokemons and then having to blacklist specific ones would become another tedius process. Configuring anything to how you want it is tedius in general so simply saving that configuration would allow you to only ever have to go through this process one time rather than every time you changed meta activities 

Example: Evolving Pidgeys is the one of the fastest ways to level but I dont typically want to hear or see Pidgeys on the map unless the focus is collecting them to evolve. In that case I may only care about Pidgey and whatever super rares I Whitelisted. Presets just lets you swap whenever you want rather than setup everytime you change meta activity

**Comment by Kraker01** [comment]
I often switch of my map (i.e. Home, Work, Restaurant...) and I'm using the mobile function (gonna open an Issues about version 0.11 and the new tunneling option), so I can't save the configuration because every time I use a different Ngrok server (configuration is only saved on my PC but I can't use it on mobile)

So I think it would be nice a notification for every pokemon popping out in the Map expert the ones insert into Hide Common
