### ISSUE TITLE
Map not working

### ISSUE THREAD

**Issue by Jerrex00x** [mchristopher/PokemonGo-DesktopMap#248]
Hello can you help me with map it doesnt load pokemons or gyms or pokestops...

**Comment by AVellucci** [comment]
can you provide some more information on this?
Screenshots, settings, logs, anything of that sort will help identify the issue.

**Comment by nosidefcp** [comment]
stoped working for me a few minutes ago also. doesnt load anything

**Comment by Jerrex00x** [comment]
Now its working but i cant change my location.

**Comment by AVellucci** [comment]
location changing while scanning does not work, you'll need to logout update your lat/lon then start it up again.

**Comment by Jerrex00x** [comment]
What is lat/lon? haha :D

**Comment by AVellucci** [comment]
Latitude & Longtitude

**Comment by Jerrex00x** [comment]
Ty its working now :D

**Comment by nosidefcp** [comment]
https://s32.postimg.org/gql4tzemd/notworking.png

not working. doesnt show anything for half an hour now

**Comment by AVellucci** [comment]
@nosidefcp are you using Google or PTC to login?

**Comment by nosidefcp** [comment]
@AVellucci google. i was trying in china and it was not wokring. in japan its working fine for now. maybe china is blocking. sad thing i found a farfetch but im softbaned and have to wait about an hour...lol

**Comment by AVellucci** [comment]
@nosidefcp there is another ticket for this specific issue #247 , it's related to google login disconnecting you after about 30 minutes, and it therefore stops the scan. Update that ticket or give it a +1 and maybe the devs will take a look into resolving that issue sooner.

@Jerrex00x if this issue is solved for you can you please close the ticket so that we don't have to wait for the devs to do so.
