### ISSUE TITLE
After the launch of Pokemon GO Live Map (ver 0.1.2) opens white window

### ISSUE THREAD

**Issue by Showmanxzzz** [mchristopher/PokemonGo-DesktopMap#271]
Please tell me how to fix it?
![screenshot_3](https://cloud.githubusercontent.com/assets/20597148/17133970/f6820642-5330-11e6-9e3e-00661434fd16.png)

**Comment by RiverGray** [comment]
I've tried following and downloading so many different things now that I can't even get THAT close to the map, tho it looked like that for a day or two before I started trying following wiki and you tube and downloading python and getting API codes and changing things by Git BASHing and a whole bunch of other things that are making me want to just throw my Surface across the floor and just give up the pokemon gig altogether (since I'm disabled a little I can't just wander around in my freetime hoping I'll come across some cool pokemons, nor do I have enough money to buy all the extra pokemon balls I cant get without help trying to find the nearest stops.

Could some Please in plain hum drum "never seen a computer before practically" language, explain to me how I can get this wonderful tool I had way too short of time with back onto my Surface please?

**Comment by mixJ2O** [comment]
Step 1: Goto: https://github.com/mchristopher/PokemonGo-DesktopMap/releases
Step 2: Click on the release you need (probably PokemonGoMap-Win.zip)
Step 3: Goto "My Computer" and click "C" drive
Step 4: Right click and create a new folder and name it "PokemonGoMap"
Step 5: Find the downloaded zip file and double click it
Step 6: Drag and drop these files into "PokemonGoMap" folder you created
Step 7: Open "Pokemon GO Live Map.exe"

Once launched, you need to sign in with your Google account or Pokemon Trainer account (https://club.pokemon.com/uk/pokemon-trainer-club/sign-up/) I would recommend creating a new Trainer account.

After that you need a Google Maps API key, the instructions are in the window, just click the link and follow the guide. Y

**Comment by mixJ2O** [comment]
Also, make sure you select "enable server" checkbox at the bottom during the first launch.

This map runs on port 8000 by default so after you have done all the above, to access it on your mobile just goto the config page of your router/firewall and enable port 8000 inbound to the local IP of your computer. Then goto your mobile and open a browser and type: http://<YOUR IP>:8000 where "<YOUR IP>" is the IP of your computer which is hosting the map.

Instructions for configuring your router: http://www.computerhope.com/issues/ch001201.htm

**Comment by Showmanxzzz** [comment]
thanks man, mixJ2O.
This Step very important Step 3: Goto "My Computer" and click "C" drive
Now work it tool

**Comment by mixJ2O** [comment]
Hey Showmanxzzz, I'm glad it's working for you now!
