### ISSUE TITLE
Adding an option to click to scan an area around the click?

### ISSUE THREAD

**Issue by milano140** [mchristopher/PokemonGo-DesktopMap#273]
hey, could you add in the feature to be able to scan around a clicked region (similar to pokevision)

thanks for the app, works the best of all so far! 👍

**Comment by AVellucci** [comment]
As nice as this feature would be, without the use of multiple accounts it would incur bans on the single account quite often if you make it jump from location to location.

**Comment by milano140** [comment]
? how would we get banned in a desktop app that isnt logged in with a pokemon go account??

**Comment by AVellucci** [comment]
The scanning account has a chance of getting banned just by running. It isn't apparent as of yet since Niantic is primarily focused on Server Stability. Once the server issues are taken care of the "soft bans" they've been throwing at players will eventually turn into proper bans. Although you are not logged in through the PokemonGo App you are sending information to their API, which still has the "Last Known Location" if you jump from one continent to the next you will eventually see your accounts being unable to connect anymore. This isn't the case just yet but will be in the future.

**Comment by milano140** [comment]
but this is just for scans i thought? i actually walk to the places the pokemon spawn lol... so your saying by using this scanning service, we could all potentially be banned?

**Comment by AVellucci** [comment]
The scan uses an account which shouldn't be your actual account. For that reason that it may get banned.
If it's not linked to your actual PokemonGo Account they can't track your real account at all, just the scanning account.

**Comment by milano140** [comment]
do u have any proof of people being banned from doing this? (i mean just taking scans...)

**Comment by mixJ2O** [comment]
Ok you've got me worried now as I just remembered that my phone which IS connected to my real PokemonGo account is on the same (wifi) network as my fake trainer account which is accessing the map scanner - I presume Niantic are logging access IPs? :-/

**Comment by AVellucci** [comment]
Being on the same WiFi will not get you banned. for example my city alone has created a WIFi hotspot for PokemonGo players that spans 29 blocks, if IP banning was a thing everyone in my city would be banned.

As for this specific application, I have not heard of anyone being banned as of yet.

**Comment by pill0ws** [comment]
You can login with multiple PTC accounts tied to separate emails. If IP banning isn't a thing then whats keeping us from doing this with one while the others maintain their own areas? I had originally thought hte timeouts were occuring because Niantic serve noticed too many logins from one account, so I made several and timeouts still occur above 6 scanning crawlers. However you can run 6 from one account with little to no problem. None of them have been banned yet from running multiple clients with the same login. I also share account info with a friend in Seattle and login with his account to capture rare stuff I find for him as well, sharing account info could be bannable I imagine. I admit I havent fine combed the ToS agreement to know for sure. My friend would certainly be over the "too far/too fast" limit moving from Seattle to Florida in about 60 seconds

**Comment by pill0ws** [comment]
So after reading the ToS, there is nothing in there that disallows sharing of accounts. So long as each exclusive app is running only one account. A friend of mine lives in seattle and we share accounts with eachother. No softbans have come of this. However scanners are prohibited in general and are listed under the same clause that hacks and bots are, so I do see proper bans coming from using the app. However, the types of bans that went out in beta were device and IP bans, not account bans. What will eventually happen is your PC and your home internet access will get perm banned. You will be forced to play normally then. If you run this app on an android then it may get banned too. At some point spoofing addresses will become a requirement to avoid these kinds of things and they may take more serious action against more serious attempts at cheating. I would certainly not use my primary account to scan areas and not use a PTC account tied to the same email address if you play with a google account

**Comment by AVellucci** [comment]
Can you share the source of your info for the Perma-Bans or IP Bans that were issued?
I have yet to see a reputable source claim Perma-Bans although I do have 3 accounts that cannot log in atm I don't believe they've been Perma-Banned.
