### ISSUE TITLE
Mobile map doesn't match Desktop (filtering)

### ISSUE THREAD

**Issue by Holli357** [mchristopher/PokemonGo-DesktopMap#290]
I haven't seen this mentioned elsewhere, but when I can get the toggle sharing to work, it doesn't capture my filtered options from the desktop.  And if I filter some Pokemon out from my phone, it doesn't save that information for the next time.  Is this something that's being fixed or am I the only one having the issue?  The older version I was using would match what the map on the desktop was showing.

Also:
- Sometimes clicking on "Toggle Sharing" just gives me a red "x" circle cursor and won't display the QR code.
- And like others have noted, I sometimes will get an error ... "no active client" or something.

**Comment by StephanBijzitter** [comment]
My filter is actually used correctly, but sadly there's no pokemon to filter on my phone... :-)

**Comment by Holli357** [comment]
Mine looks like this:  http://tinypic.com/r/1tspcw/9
And I want it to look like this:  http://tinypic.com/r/im81oi/9

Kind of a big deal!  :smile:

**Comment by rhawley88** [comment]
filtering is currently not carried over and has to be re added on mobile i hope in later date they change it but for now just have to re-enter the info to mobile

**Comment by ohiotech** [comment]
Understood that filtering is not carried over, but is there a way to create and load a script to either keep on and for the mobile device, on and for the desktop, or both? The script could be used in place of the drop down. As it stands, the list can get so long, and because it doesn't scale or scroll, you can't enter everything you want. A script could be made for what to filter out, as well as what to alert for. Just a thought.
