### ISSUE TITLE
Perpetually Waiting

### ISSUE THREAD

**Issue by Beefycake** [mchristopher/PokemonGo-DesktopMap#293]
I haven't been able to use this app yet. First downloaded 0.1.1 and was just going to wait for the next updated to see if it worked. However when my friend told me there was an update available, there wasn't an update link on the program either. So I came here and manually downloaded the update, but still get waiting, never operational. Anyone have a idea of what could possibly be wrong?

**Comment by luisitoortiz** [comment]
Have the exact same problem.  I extracted the folder for 0.1.2, did everything I was supposed to, and got the eternal waiting. Today I tried 0.1.3, and again, eternally waiting.

Windows 10 64-bit
Chrome 64-bit

**Comment by Holli357** [comment]
Yeah, same here.  Tried Version 0.1.2 this morning ... waiting.  Downloaded the new Version 0.1.3.  Still says waiting - or won't log me in at all.

**Comment by AVellucci** [comment]
Can you provide your console log?
once you load the app, click on "Tools>Developer Tools"
From the tools it opens copy your log and provide it here, with your login method, PTC or Google.
I noticed that with Google it keeps loading after this error, whereas with PTC it hangs there.

> Got location: LAT, LON
login.html:267 Starting Python process...
Navigated to file:///C:/Users/USER/Desktop/PoGo-Map-v0.1.3/resources/app/main.html
main.html:157 server up
main.html:199 Error: Cannot call loadURL because the webContents is unavailable. The WebView must be attached to the DOM and the dom-ready event emitted before this method can be called.(…)
