### ISSUE TITLE
[request] Import/Export Filter List

### ISSUE THREAD

**Issue by tokyotapes** [mchristopher/PokemonGo-DesktopMap#295]
Just had to manually re-enter all my desired Pokemon in the filter list.  Don't see an easy way to back that up.  It would be cool if you could import/export a CSV of Pokemon to the list.  The way it works now with the autocomplete is awesome btw, helped a lot.

**Comment by tinarazzburton** [comment]
It also would be much nicer if we could just pull up a list and add checks next to the names we want to filter.  The current system is a bit cumbersome.

**Comment by ranrinc** [comment]
+1

**Comment by Holli357** [comment]
Yeah, I'd even be fine with entering the numbers again.  That way I can just keep the comma separated numbers in a document and copy/paste.

**Comment by gonjiak** [comment]
they got lost because the list itself now gets saved in another file. As for now, i would suggest you to do the same as me and make a backup of the file with the lists, for windows it's located here, but i don't recommend to modify it directly:

%user%\AppData\Roaming\pokemon-go-map\Local Storage\http_localhost_8000.localstorage
