### ISSUE TITLE
Output all instances to the same map

### ISSUE THREAD

**Issue by thappy** [mchristopher/PokemonGo-DesktopMap#307]
If I run multiple instances of this program, can I force them all to output to the same map?

**Comment by AVellucci** [comment]
This would be a cool feature to have.

**Comment by dannay1** [comment]
Mine already does this, and i'd actually rather it didn't. I've tried:

- running my instances under different google accounts
- running instances from different install folders on local machine
- running instances using different google API

and they still all show up under the same map. This is troublesome, because I am letting my brother use it in England, and now if I set up notifications, I get notified when something pops up on his and vice versa.

See screenshot for 3 different circles of scans all showing up within the same app (even though these are actually coming from 3 difference instances)

![image](https://cloud.githubusercontent.com/assets/20685352/17180293/f07b038e-53e9-11e6-8fc8-de3b7c9580f3.png)

**Comment by PhantonQuad** [comment]
That is quite cool, do you know what file to change the external port number in? so I can allow multiple connections in on multiple instances using different accounts. Or do you use the Mobile - Share feature?

**Comment by dannay1** [comment]
I use the Mobile - Share feature. Since it creates a new random url each time, I set up a tiny.cc account, which allows me to create custom urls. Then, if I have to restart the server for whatever reason, I just go back to tiny.cc and update my custom URL. Thus, for me tiny.cc/pmongo-daniel (not real, but you get the idea) always points towards my session, and tiny.cc/pmongo-matt is always for my brother. But like I said, this means we can't use the notifications because we are in different areas and they fire no matter where the monster appears on the map.

**Comment by PhantonQuad** [comment]
OK great idea, this is great for me even with the notification issue as I tend to filter down when I'm hunting. Thank you for that!

**Comment by dannay1** [comment]
You are welcome, hope that helps!

**Comment by AVellucci** [comment]
maybe have the notifications only sound if they're found in a radius from your current map center.
So if I pan south of my search area some of the northern most spawns won't notify.

**Comment by dannay1** [comment]
That would be a great fix actually, then it wouldn't matter. Wonder if someone can implement that?

**Comment by AVellucci** [comment]
Depending on how the notify checks for Pokémon a Radius or some distance filter could definitely be possible.
