### ISSUE TITLE
Logs in fine, however, stuck on "waiting"

### ISSUE THREAD

**Issue by shadowedlab** [mchristopher/PokemonGo-DesktopMap#330]
On the recent version, 1,3, it logs in correctly, however no map shows up, just a white screen, with the buttons and menus working. I don't know much about coding, but one error shows up in the console sections, reading:

Error: Cannot call loadURL because the webContents is unavailable. The WebView must be attached to the DOM and the dom-ready event emitted before this method can be called.(…)

Hope this helps further the program and fix the issue :)

**Comment by SamuriBakePie** [comment]
Is this on your computer of mobile device?

**Comment by shadowedlab** [comment]
Computer, windows. However, people are experiencing server issues, so it may just be on PoGo's end. Ill wait till it's more stable and check back in.

**Comment by rcolanero** [comment]
I appear to be getting the same error, below. Google API key works the fine in the OSX version but the Win version gives just white screen instead of the map

Error: Cannot call loadURL because the webContents is unavailable. The WebView must be attached to the DOM and the dom-ready event emitted before this method can be called.
    at webview.loadURL (C:\PokemonGoMap\resources\electron.asar\renderer\web-view\web-view.js:409:15)
    at serverUp (file:///C:/PokemonGoMap/resources/app/main.html:195:21)
    at EventEmitter.<anonymous> (file:///C:/PokemonGoMap/resources/app/main.html:158:9)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)

**Comment by shadowedlab** [comment]
An issue with the win version maybe?
