### ISSUE TITLE
Mobile activation

### ISSUE THREAD

**Issue by Pateedo** [mchristopher/PokemonGo-DesktopMap#339]
As an iOs user how am I able to use mobile notifications? Are there any guides how to enable it?

**Comment by JaymerJaymer** [comment]
I'm not quite sure how that whole thing works either.
If you launch with the "Server mode" checked at the bottom, then why go to mobile and enable?
.... since you're already in server mode.

And whats that barcode scan for?
And whats the URL for?
And why on OS X does another window popup when I click the URL, but it doesn't update?
