### ISSUE TITLE
Outage Error?

### ISSUE THREAD

**Issue by sknguyen** [mchristopher/PokemonGo-DesktopMap#403]
Since last night (about 12 hours ago), I'm constantly stuck on 'Outage' and not able to scan.  Anyone with a quick fix or experiencing the same problem?

**Comment by al3x-edge** [comment]
@sknguyen Currently experiencing outages every so often here.  Most likely not an issue with the app if it's reporting an outage.  You can open up your developer tools and check the console to see if it has Niantic errors being reported.

**Comment by pocketq10** [comment]
im getting more outage experience with the newest version as well. switching back to 1.3 until it get sorted out.

**Comment by Hearttless** [comment]
I think it happens when you enable fast scan. It must be a glitch with the patch. I tried turning it off and it seems to work fine for me for now.

**Comment by LesBean** [comment]
I was / is having the same issue with fast scan on or off, after about an hour of the application running it would just stop scanning all the scanned areas would slowly turn red than disappear, i had to restart the application for it to start scanning again

**Comment by majuss** [comment]
@LesBean thats the exact same issue I have and I think everyone have this issue on every platform... After about 60 minutes the scanner just stops working and you have to logout and in again.

**Comment by lmnottingham** [comment]
Are you actively viewing the map, is it running in the background, or are you AFK and the computer has gone to sleep or something? If you look under console:
2016-07-30 20:44:10,783 [        models] [   INFO] Upserted 0 pokemon, 0 pokestops, and 0 gyms
main.html:167

2016-07-30 20:44:15,806 [        search] [   INFO] Search loop 4 complete.

2016-07-30 20:44:15,806 [        search] [   INFO] Waiting 5 seconds before beginning new scan.
main.html:167 

2016-07-30 20:44:20,808 [        search] [   INFO] Search loop 5 starting
main.html:167

2016-07-30 20:44:20,808 [        search] [   INFO] Skipping Pokemon Go login process since already logged in                 for another 1122.19 seconds
main.html:167

2016-07-30 20:44:21,071 [        models] [   INFO] Upserted 0 pokemon, 1 pokestops, and 0 gyms

I am very new to programming and have no clue what any of this really means, but it seems like maybe if you arent physically on the app when that time runs down it will re-log you in once or twice but if you don't look for a long time it will stop? Or maybe the google authentication expires?
