### ISSUE TITLE
Great Potential! Working Perfectly! Just needs 1 MORE THING!!!

### ISSUE THREAD

**Issue by hunion99** [mchristopher/PokemonGo-DesktopMap#430]
Since we now know the API clock thing is in the new update, and everybody is scrambling to find a good alternative, the 5 second delay works fine, 
but
I feel if you add the capacity of 2 accounts getting info from the server simultaneously, that would double the rate, and additionally scan areas more quickly so that those rare pokemons are discovered more quickly, so more time to go after them.

An algorithm like that would be groundbreaking.

**Comment by psychoblue** [comment]
The massive slowdown is making finding rare drops much more difficult.  :(

**Comment by Layzmaster** [comment]
If possible this would be great as I used to use this to search large areas for nests and now is essetially worthless for my use.

**Comment by abuch47** [comment]
I was having heaps of luck last night, after the 100m to 70m change on 0.1.5 running 4 threads (2*2 PTC)
still finding rare spawn with plenty of time (dragonite with 15minutes) this morning after PoGo update still runnign 0.1.5 it is terrrible find the rare spawns somewhat less frequently and always <2mins left on timer.

I havnt tried 0.1.6 due to slower scanning speeds but is it good?

**Comment by pill0ws** [comment]
So far it seems more stable, I dont get a huge popup of errors at the start. The scan speed is horrendous and I havent tested it with "Follow Current Location" My problem with 0.1.5 was updating location too frequently reduced scan radius. With the even slower speed on 0.1.6, it sounds like it would be impossible to use "Follow Location" with any degree of efficiency. I'll test it out tonight. I am tempted to run 1.3 as that was the most stable version before the Win.exe versions. So far 1.2 is hands down the best but the tunnel service sucked on 1.2.

**Comment by Gnaj** [comment]
You can actually run 2 accounts at the same time even 3, just open another instance of the app and log in with a different email and done, u can minize the extra maps and keep just one main map open, it will show everything

**Comment by pill0ws** [comment]
What is the new "sweet spot" for radius? I had it all timed out before and now scan speeds are much different.

**Comment by pill0ws** [comment]
Correction, 1.3 is not missing any spawns at all and searching at the original 5s rate

**Comment by calgar** [comment]
@hunion99 actually that's what I'm doing.   I'm running 2 instances over the same area with a start time difference of 2-3 minutes.. so far so good.. and it keeps my honeycomb in a better shape.. so definitely your idea might help if not to "speed it up" at least to keep the area healthy

**Comment by calgar** [comment]
also... those honeycombs with the same settings used (Radius 10) touched each other on 0.1.3.   Did the area got smaller by any chance?

**Comment by rdthp** [comment]
log in screen.....scroll down and there it'll be. default is 7.

**Comment by hunion99** [comment]
lol.

**Comment by abuch47** [comment]
for a 20 setting 5minutes and 16 seconds was perfect for two accounts running two scans each.

**Comment by SmilinItalin** [comment]
So i was trying a few things ......running 20 is way too much.....i know i set it at 6 and it keeps a perfect update. So last night i was playing with a few things one was doing a new program ever 2 to 3 min (at 20) was working fine for about 30 min got up to running 15 then the first 3 crashed......but it was keeping up with a constant scan of the area.... lol.......so tonight ill try running multi scans all mini's at 6 and just set them up to touching lol

**Comment by AssKetchummmmm** [comment]
So I've actually not thought of running multiple instances of the app and it sounds like a great idea. Curious though on whether you have to constantly swap between Windows. Sounds like a pain in the ass. 

@calgar when you have two scans of the same radius in the same area does it refresh both scans more often?? Or do you mentally combine both scans and search for whatever Pokemon you are looking for?

Also I'm not sure if the scan pattern has always been the same but after selecting "Scanned Locations• I've noticed the spiraling honeycomb that you all are talking about. I'm also noticing that as the spiral grows larger that the center portion doesn't update anymore and the honeycomb pattern actually disappears. I have to usually logout and log back in to refresh it. 

I live in Charleston SC where using "20" for radius covers nearly all of downtown and I can see everything. Any way to continue to efficiently use 20??

One more thing, I've just figured out the portforwardibg/server access feature and love it. Personally like it better then Mobile feature. Any way to still use this feature if I have multiple scans or instances of the app running like @calgar and @hunion99 stated??

**Comment by abuch47** [comment]
Yes 20 setting takes 21 minutes for a full scan and to start back again. 

This is why I run 4 scans (2*2 PTC) reliably over a 20 setting radius and it covers every area in 5min16sec so theorectially i should have found every pokemon with at least 9min44sec left on the timer.

20 setting is perfect for me in suburbs as it allows a max 3km/10minute drive radius. It picks up the rare slawn hotspots in my area and Pokemon on the outer fringe I can decide if I really want to drive that far with a chance of not getting there in time.

I am at 124 pokedex now but of the scanned pokemon I have missed that could be at 133. Its possible to get 145 currently so thats 12 that still havnt spawned/seen with 3 of them not being very likely due to region exclusives.

**Comment by tinarazzburton** [comment]
opening two instances might work, but if you are using it on your mobile device, wouldn't that mean you'd need to set up two separate tunnels and toggle between the two switching the scan location on both?   

In other words, I could set up two instances and have them both scan around my house no problem.  But if I'm out and about in the city, the idea by the mobile app is that I can set "follow location" and it will start scanning a radius around my current location.  So I guess I'd need to set up two tunnels and move both to my new location as I move around.   I can see how having two logins for one instance of the app would be beneficial, because both could move and scan based on your new location.

**Comment by DyonR** [comment]
So, if there comes a option where you would be able to use multiple accounts for scanning, I think it would be a good idea if you could combine multiple of them to 1 worker. For example, fast scanning did 4 circles every 3-5 seconds. So if we could use 4 accounts at once, we would have 'fast scanning'.
I made a quick visualization of how it would work. Each number represents another account.
![multiple pokemon go accounts](https://cloud.githubusercontent.com/assets/16341409/17276203/164070d2-5722-11e6-896d-8fdad1985af5.png)

**Comment by Arceus** [comment]
@DyonR This. Multiple accounts scanning is the only solution. They way it works now it's barely useful.

**Comment by capgames** [comment]
you would need 5 accounts, its a 5 sec scan time, so you have 5 accounts then you have a secment added/updated each second

**Comment by hunion99** [comment]
Is there no possible way of increasing the search radius of each possible scan?

**Comment by hunion99** [comment]
Also, how do I port forward this map so I can view this as a single map online from anywhere?

**Comment by abuch47** [comment]
Im still going ok with 4 fast scans on 0.1.5 (2*2PTC) with a 5 minute buffer on radius 20. Not as good as it was but much faster than 0.1.6 one slow scan.

You can open multille instances of the same versions and it will collate no matter whether a different PTC is used. So mobile can see all the scans. Whereas if i open 4 1.5s and one 1.6 for mobile i wont see anything but 1.6. I downladed a qr reader as well to make mobile easier. Not that i really use it.
