### ISSUE TITLE
Well Done!

### ISSUE THREAD

**Issue by lucasxvieira** [mchristopher/PokemonGo-DesktopMap#431]
Version 0.1.6 is actualy the best one at the moment, it's scanning super fast for me and i'm loving it! keep it up!

**Comment by psychoblue** [comment]
What scan radius are you using... I'm getting 1 scan circle every 4-5 seconds.

**Comment by meelokun** [comment]
I would like to know as well, getting 1 scan circle every 4-6 seconds... Painfully slow

**Comment by pill0ws** [comment]
I reverted back to 0.1.3  myself. 0.1.6 looks great, however there was a change to the base scanner to make it scan one node at a time rather than chunks of 3. I can literally drive down the road and scan faster than the scanner in its current state and simply walking constantly resets it. Right now it is great for lure farming or gym battling. Anything where you dont move enough to trigger a location update and reset the scanner. The settings in 0.1.3 seem to still work as they did in terms of speed and accuracy. You can also still have multiple scanners setup however it seems now that you need to sign in with a different account for each one if you weren't already. After a few tests, the more areas you attempt to scan with one account, the less that show up in any of the scanned radius. I got 3 running and then with a 4th I scanned a small 6 block radius and saw literally nothing. I switched accounts and all sorts of things popped up. 

It would seem that with this recent patch to the game they also made some tweaks to how it works itself. I've noticed that I have to go much slower for things to pop up on my screen now, I maybe just imagining it but it really feels like the speed to trigger a response has been set at a lower threshold.
