### ISSUE TITLE
Inconsistency with spawns in new/older versions

### ISSUE THREAD

**Issue by kdichev** [mchristopher/PokemonGo-DesktopMap#438]
I can see different spawns from last versions to the new one. 

New version has spawns that are not shown on older versions and vice versa.

There should not be a difference as the api response from Niantic servers should be the same when a scan is complete? Right?

**Comment by Narazna** [comment]
Niantic changed some stuff in the most recent version.

The distance you can detect pokemon around you is now 70m and you can only ping to check for pokes every 5 seconds.

This means the older versions of the program might not work at all, or if they do they will not be accurate.

The newest release works perfectly, albeit a little slow, but there is nothing we can do it about it now because of the 5 second change.
