### ISSUE TITLE
Scan Rate

### ISSUE THREAD

**Issue by Oh1o** [mchristopher/PokemonGo-DesktopMap#444]
You may have slowed down the scan rate to find pokemon. But the refresh rate on 1.2 was ideal, this new one is only useful for a scan radius of like 4 or 5, anything more and it takes way too long to scan back through the area as it will take 10 minutes which is the spawn timer for pokemon.

**Comment by milano140** [comment]
agreed... cycling through a 7 radius, and you may only find pokemon that have recently been scanned only have a time of 7 mins left before they disappear, scan radius in 1.2 was perfect, if OP could find a way to get back to that, that would be great!

**Comment by externuz** [comment]
Where do you specify radius, guys?

**Comment by Chingonzly** [comment]
On the login screen

**Comment by Chingonzly** [comment]
I'll just ask here instead of posting new issue:

So is this why my scanner doesn't always show every pokemon inside the radius? Mine is set to 10.

**Comment by cyan** [comment]
yea but since niantic is adding security to their system.....scanning to fast will be a problem really soon :/

**Comment by pocketq10** [comment]
definitely 1.2 scan is a lot faster. but not as accurate. hopefully the scan doesnt cost me a dragonite haha.

**Comment by Doyoueventraps** [comment]
yea scanning is so much slower in 1.6

had to change radius down to 7

**Comment by pill0ws** [comment]
even a radius of 7 will not work under Niantics new security measures. Your speed is measured by the distance traveled between each update. You can only trigger discovery at that speed so you have to be within a distance from your last node that calculates to around 25mph, otherwise no events are triggered. it also seems like you have to be going that speed for a couple updates before it will start triggering again once it stops. A radius of 3 even triggers this speed issue upon resetting a search cycle. What is needed is either a helix shaped scan pattern that oscillates or click to scan small 2 block radius that will only perform a scan one time and forces a delay before accepting a new scan. Right now the game is paying close atttention to your speed, they've basically nerfed driving. Going to fast gets you nothing at all

**Comment by JaymerJaymer** [comment]
using 3 radius just now i have many mons that appear with 3 mins or under.  2 long battles elsewhere and by then you've got 30 secs to pick between 2 mons disappearing in 30 secs.  its def. frustrating for sure - but better than walking around out in the heat :)

**Comment by PhilipposVassil** [comment]
still using 1.2 because i cant run the full exe files in the new versions because my antivirus found virus after I run the program and I don't want running it if isn't safe...I don't know if is safe or not and its false alarm by AVG
hopefully the 1.2 exe is safe so i still using it and it still work well :)
it can find all the Pokemon nearby!

**Comment by AVellucci** [comment]
@PhilipposVassil There are no insecurities with this program, the virus detection from AVG is a False-Positive.

**Comment by PhilipposVassil** [comment]
@AVellucci Are you sure? Because in IT lessons told us to trust it because sometimes tell us the truth.
In a lab show as a file that is created by them and test it in 2 different antivirus one has found it and the other not...
That why i am so careful about it

**Comment by AVellucci** [comment]
I won't discuss Anti-Viruses and how they work here but I can confirm as an experienced IT Professional that the Malware that AVG is detecting is a False-Positive.

The `.nuget` has the same files in it as the `.exe` except that the `.exe` will use an installation script instead of extracting files.
