### ISSUE TITLE
[Suggestions] Way to increase scanning speed drastically

### ISSUE THREAD

**Issue by minim8** [mchristopher/PokemonGo-DesktopMap#455]
Simple as it is, give multiple login/api options so that people can use more (maybe up to 5?) accounts simultaneously. Merging the data shouldnt be too hard/slow and thus, if the positioning works correct, result in an increased speed of almost up to 500%. 

And thanks for updating the app to the new situation so fast!

**Comment by Kirbay** [comment]
It's not that simple, when your first account finishes its first scan and skips over the other 4 scan circles, it'll trip the speed detection. This could work if you scanned in some new pattern though. You would just have to completely remake the step algorithm, maybe some concentric spirals nested inside each other, with you could do with logarithmic spirals. But that's a bit too much for a guy that only made it through algebra 2 in high school :3

**Comment by pill0ws** [comment]
There is no more scanning quickly, the game itself doesnt trigger the events. You cant even trigger pokemon battles above 25mph now.... they basically nerfed driving and as a result nerfed fast scanning. Scanning now will be forced to move at the same speed as the game considers "walking" or there will be no event notifications. The scanners will need to completely remove autoupdating the scan cycles as anything above a 2 radius triggers the speed detection. People who use scanners will have to use them for very small areas, about the size of a Walmart parking lot . The scan pattern needs to oscillate rather than start over fresh for to not be considered moving faster than allowed. Spiral is also very time inefficient now as it always included dead space. Spawn points are static and finite. Once logged you would only need to connect the dots to scan an area

**Comment by minim8** [comment]
What am I missing here? Stay with the same Figure and take the total number of steps like it is. (Radius 5 should have like 61 steps since its 1+sum(k*6) with k_max=radius-1. Could be that im wrong with this number I didnt look at the figure or code but still, there is a detectable, constant number of steps for each radius) 

Thus just divide the total number by the accounts available and let each one do the scanning, seperately starting at the according "starting points". In our example (Radius 5, 5 Accounts+Keys) starting points could be something like 1 13 25 37 49. So if we would be able to combine and display this seperated data in the app, we should even be able to use the old algorithims with only slight adjustments. 

Was there anything else than the updaterate beeing limited to 5s and the radius beeing reduced to 70? Because if not than the above way might work and take 60s instead of 300s. 
Why should it trigger anything when the speed limit of each seperated account is within the limits? Its just a matter of combining the datasets.

**Comment by DavidBabel** [comment]
Not easy for sure, but definitly the best way to speed up the scans
