### ISSUE TITLE
Lat/Long shows incorrect location on map

### ISSUE THREAD

**Issue by gnedved** [mchristopher/PokemonGo-DesktopMap#46]
What the app shows:
<img width="630" alt="bad_lat_long" src="https://cloud.githubusercontent.com/assets/3418675/17009923/58781e12-4eb4-11e6-9832-305bbfc05814.PNG">

What google maps shows:
<img width="461" alt="right_lat_long" src="https://cloud.githubusercontent.com/assets/3418675/17009927/5fc36cee-4eb4-11e6-9d99-6c0b4a450aee.PNG">

I hope this helps, the map does show the same town but it seems to be like 5 miles off.

**Comment by dittowill** [comment]
im having the same issue, it shows some place close but not where i am.

**Comment by because-bot-fed** [comment]
I believe I've found the issue.

It's something to do with how many decimals are used to represent your location.

When I was using a previously noted down set of coordinates with 5 decimal places, it put me out in China. 

When I cut off the last decimal, my location was a smidge off (because rounding) but correct. 

If either of you could test and report back it'd probably help him fix! :)

**Comment by gnedved** [comment]
I tried with the 4 decimals, still getting the same problem. It is just a few miles off, which unfortunately makes it not very useful for my current location.
<img width="1080" alt="distance_difference" src="https://cloud.githubusercontent.com/assets/3418675/17011684/1fc056b4-4ec5-11e6-8d7f-4246632ac782.png">

**Comment by gnedved** [comment]
The newest release 0.0.7 fixes my issue. Thanks!
