### ISSUE TITLE
[suggestion] Solution to slow scanning issues

### ISSUE THREAD

**Issue by asavage44** [mchristopher/PokemonGo-DesktopMap#460]
As you may know, pokemon go works by having spawn points that spawn pokemon at the exact same location at the exact same time every hour. So if a pokemon shows up at a location at 11:41 another pokemon (usually different) will show up there at 12:41, 13:41 etc. 

The scanner could create a database of spawn locations and times in the first hour it is running and then just scan spawn locations 15 seconds after each pokemon spawns. The database should be something it loads each time you open and could be transferred to future versions.

The benefits of doing this are huge. The user gets the full time to catch the pokemon. The scanner needs to scan much less often so you can cover a larger area, etc.

The only issue I can think of is maybe if locations spawn at the same time not near each other there could be issues using only one account to scan locations far apart. Some delay might need to be put in or use multiple accounts to scan.

**Comment by dhernandez98** [comment]
Yes. That's possible. But If I'm not wrong, Pokemon's nest changed just yesterday. What if Niantic change them again?

**Comment by pill0ws** [comment]
They cahnge regularly. There is a golf course near me that spawned Sandshrews all the time all over the place. It has been Pikachu for 3 days now and no sandshrews. I am willing to bet it changes again. IT would make sense to rotate these things because some regions lack access to certain species. A nest rotation is a good way to ensure everyone can catch em all... .eventually

**Comment by 141** [comment]
I've staked out areas for hours, I saw no pattern repeat. The only thing I do notice is one of two things possible, either I clean out an area of the pokemon I want and then less show up, or more start spawning after I collect the little bit that's there. So, maybe it's by popularity in some areas. Truly busy areas may have a pattern.

A more optimal solution would be to specify individual scan spots. And cycle scan those areas, going at most 20mph. This would be optimal for me, since areas I'm scanning have a lot of sparse areas for less common pokemon.

**Comment by asavage44** [comment]
I only tested this for a few hours on Friday but it worked perfectly. There is a pokemon spawn location that spawns a pokemon exactly at :41 every hour that I can catch from my desk. I used a now defunct website that let you click a location to scan and wrote down all the locations and times nearby. I had 100% success on them spawning at the same location and time every hour. If it does change every day or few weeks it doesn't matter it just needs to do another sweep and once a predicted spawn doesn't occur the program would know it needs to do another sweep of the area. It could also continue to scan during gaps when no pokemon are predicted to spawn.
