### ISSUE TITLE
MultiAccount + MultiThreading like PokemonGo Map ?

### ISSUE THREAD

**Issue by jfabri63** [mchristopher/PokemonGo-DesktopMap#462]
Hi
I wanted to know if you can implements those feature to improve drasticly the scan search time. I just tried and it's super fast but I still prefer your version of pokemongo Map :+1:

**Comment by aldarund** [comment]
You tried what?

**Comment by MrAwesomers** [comment]
I've created 3 PTC accounts and lined them up so only 1 corner would touch. I'm scanning entire cities like this and I never stand still longer than 15 minutes to catch a rare pokemon. Getting the positions right is a mess though, but the scanning works perfectly. I would love to see this automated to max 5 accounts so that you click 1 location, the other four accounts would automatically go round the center. This would solve the slow scanning and increase the effectiveness because smaller areas are scanned more frequently. Letting 1 location spiral. like it is now, will result in you missing pokemons because it's slow. I love this app!

**Comment by abuch47** [comment]
what setting do you use for this?

**Comment by minim8** [comment]
Yea, but by making only one corner touch, you also miss big parts of the area in between dont you? you could also use these multiple accounts to start the same spiral but in a kind of delayed manner of eg 12 steps so that you have the old form/structure of the algorithm and update every circle once a minute which should be sufficient to find the pokemon

**Comment by abuch47** [comment]
This is what i do and was the best method before changes still is for me. Im thinking of going slow scan and even more accounts because its more accurate but dont have the patience.
