### ISSUE TITLE
1.3 or 1.6? Need help

### ISSUE THREAD

**Issue by TheFalseKing** [mchristopher/PokemonGo-DesktopMap#486]
Hi. I'm trying to decide between which release to use. I've gone through a lot of the threads to try and get a better idea on how to proceed. 

Should I be using 1.3 for the 5sec scan even if it might miss some pokemons or should I use the 1.6? Either way I plan to run 2-4 PTC accounts with it to get optimal results.

Advice or help is welcome.

**Comment by AVellucci** [comment]
With the new restrictions by Niantic it's probably best to run multiple instances ate a Radius of 2 or less, instead of 1 instance at Radius 5~
You're free to use whichever version you'd like but keep in mind the Speed Nerf is a new feature and if your scanner moves to fast no pokemon will appear.
I would suggest 1.6 with multiple accounts and small areas instead of the older scanners with 4 - 5 scans at once tripping the speed fix.

**Comment by TheFalseKing** [comment]
Is it possible to run multiple scans and have them on top of each other? So long as they are spread out by a length of time? I read that someone was saying they use a radius of 20, but they have 5 accounts spread out with a time of 5.16 each to cover it.

Is there a maximum amount of accounts you can run with one api map key?
