### ISSUE TITLE
1 API, 4 PTC accounts, 2 scanners stop working for no reason

### ISSUE THREAD

**Issue by TheFalseKing** [mchristopher/PokemonGo-DesktopMap#503]
Sorry if the title is a bit ambiguous. I have 4 scanners in remotely the same area and for some reason 2 of them like stop working. It usually starts to happen when I try to move 1 of the 4 around to get it working again and the other just stops. I'm not entirely sure what's going.

If you can only run 2 scanners at the simultaneously on the same api map then I know, but if you can run more then any help would be great.

**Comment by pill0ws** [comment]
Niantic has done things on their end to try and eliminate scanners. If you want to run more than 1 scanner you will likely need to spoof all sorts of data. Chances are it is tied to IP address and/or geolocation data. when you move one you trigger a safeguard that recognizes that human beings can not travel that fast. The scanners immediately start scanning again and they will not work again until furhter safeguards are bypassed.

I played with two devices previously, an older iphone and a android nexus 7. When I am logged in with both of these devices just playing the game notmally, I do not get encounters pop up on either until I log out with one of them. They are both wifi connected to a hotspot on my windows phone, I got to this point because I couldnt simply install the game on my normal phone. So it seems like shared geolocation data is restricted now and it could be IP related as well but I notice when I feed my geolocation data to the APP that the 'no encounters' thing tends to occur again. So I suspect something related to geolocation is also being monitored by the game now

**Comment by Mirx** [comment]
Just enable the "toggle developer tools" and check the console log. You'll see the response to the login attempts.
The ptc servers are having some difficulties.

**Comment by TheFalseKing** [comment]
I can't really tell if all 4 are going since I have no idea if each console is separate from the other. It seems there are a lot of Database locking going on. I was hoping to make a few 2-3 radius accounts and put them near one another but now I have no idea. Maybe I should try for the speed and inaccuracy I might get from 1.3

**Comment by MacDogg** [comment]
I have the same issue and here are a few bits of information that might help.  I have 4 gmail accounts, 4 different API codes and I have the app running 4 times with the 4 different accounts, search area 7.
From Developer Tools just after it stopped scanning and the circles started disappearing and not refreshing (screen shot included):
2016-08-01 17:24:25,315 [search_thread-0][models] [INFO] Upserted 2 pokemon, 196 pokestops, and 5 gyms main.html:168
2016-08-01 17:24:30,562 [search_thread-0][search] [ERROR] Search thread failed. Response dictionary key error main.html:168
The one that stopped was the upper left one in the marker screen shot.  I noticed in the middle at the top it said OUTAGE in red.  After I logged out and logged back in with the same marker point/API/gmail account (I have the lat/long saved) it gave me an error (sorry, no screen shot, will try to get that next time) and it placed the marker in the far right position but you can see the upper left one has started over where it is actually scanning with the fresh green circles in the middle.
![log](https://cloud.githubusercontent.com/assets/20782190/17311223/2956352e-580f-11e6-86ad-0996e90abfc7.JPG)
![marker](https://cloud.githubusercontent.com/assets/20782190/17311232/343dae86-580f-11e6-986c-e387b0ef874c.JPG)

**Comment by hoeguard** [comment]
Niantic has taken measures to prevent scanners. This is not an issue with the application, it is an issue with the way it is being used.

**Comment by MacDogg** [comment]
Thanks for the info.  Guess we should only use one, maybe two at time in close proximity.

**Comment by pill0ws** [comment]
Basically, the only way to use it at all now is to not be logged into the game on the same IP, if you swap large distances you need to scan the same node a few times before the failsafe will let you start seeing things again (this is a theory, I noticed issues with the game triggering encounters whenever I updated the App with my geolocation. the little target icon on the map seems to feed your geolocation to the App that is scanning and the game seems to know it is tied to my personal geolocation on my mobile device. So it creates this situation where I cant get it to start picking up encounters in game until I toggle off follow location and reset the ngrok tunnel in my browser. I noticed this issue as well with my tablet. When I power it down and then back up, If I am moving when I do so, the game will trigger nothing at all until I slow down to a crawl for enough time to ping the same area about 3-4 times. I think it likes you to stop moving before it decides if you are not a bot. When I run my iphone as well as my android, I get similar errors where the game will not trigger monster encounters. So this shit is deeply ingrained, if you want a scanner app now you have to work around these restrictions. Sadly, it still works better in a tiny ass radius as a toggled tool than the shitty in game tracker does. It's kind of worth it to avoid the hassle of running around in circles to find some stupid  rare.

**Comment by pill0ws** [comment]
You likely need t oalso spoof an IP address for each google API and you need to force the app to ping the same area multiple times upon reseting the cycle or you need to create a pattern that doesnt trigger the long distance game failsafe. An oscillating Helix would still let you blanket areas without triggering the gap jump problem

**Comment by Mirx** [comment]
Your going overboard with the anti-bot measure theories. The Google API part is completely separate from the PokemonGo API. It's just used to generate the map shown on your mobile, and has no correlation to the information being sent to Niantic.

If I drag the marker around 1,2 km / 0,7 mile, the first scan is still returning hits. You can easily verify this from the console logs.

Running a radius of 3, the first scan of the additional loops is still returning hits. You can easily verify this from the console logs.

Driving at 50 km / 31 mile per hour (residential speed limit where I live) still triggers encounter events.

Being on the same IP with a map and an active game isn't an issue. Don't know if additional sessions would, but imagine a corporate building where everyone is behind the same firewall/IP. Haven't been in the office yet after the change, but there are literally dozens of people playing with the same IP, which then should be an issue.

**Comment by pill0ws** [comment]
login with multiple devices and try and trigger events. I have both an android and an ios running the game at the same time. At a certain speed, both will trigger less and less events, even of commons, I was practically standing on a Pidgeot spawn and it would not trigger. With two devices running from the same IP (on the same account) I have to drive slower for things on the road to spawn. Almost literally the moment I shut one off things start to trigger everywhere. I am hotspotting these two devices from a 3rd. When I feed my geolocation into the app to move the scanner, literally nothing spawns at all. I am straight up creepin but the moment I unhook the location on the device running the app, things start poping up everywhere.

Heres another interesting observation from playing the game on two devices in general, when you put an android into sleep mode it keeps the game alive so when you turn it back on it tries to resume. When I turn off one device like that so that the other can remain effective and then later turn it back on. If I am mobile when i turn it back on things dont seem to immediatley start spawning again when I turn it off. If I stay mobile things continue not to spawn. When I stop it seems to cancel the effect and can spawn encounters normally again.

They did some shit, we dont know what, I cant play with two devices anymore, it was cool for doubling up on capturing but that seems to effect the game now. I imagine there are quite a few triggers to their security measures. There does also seem to be a few releases to it as well though. I believe this project has been abandoned though and can't say I blame the devs if thats the case. Ultimately it was expressed that Niantic doesnt approve and they certainly took measures to break the things that were working.

**Comment by Mirx** [comment]
I don't know whether it's dead. The project this is based on is still getting new commits.

https://github.com/AHAAAAAAA/PokemonGo-Map/commits/develop

And there were still tags being added to issues 11 hours ago, so at least some of the devs are still online.
