### ISSUE TITLE
I have java-script error.

### ISSUE THREAD

**Issue by Harsh1Acerider** [mchristopher/PokemonGo-DesktopMap#515]
![capture](https://cloud.githubusercontent.com/assets/20783111/17312924/a00e5fd8-5874-11e6-91a5-7673a79d4c5b.JPG)

**Comment by G0KUSS4** [comment]
I'm getting this same error.  Windows 10, but I did just update my Java.  Don't know if that has anything to do with this.  Didn't seem to start until I did.  Running Java Version 8 update 101 (build 1.8.0_101-b13).

**Comment by MacDogg** [comment]
This is the error I get after one of the scanners stops working when I have three or four running and have to restart that one.  If you look at the code, it says Error: Listen EADDRINUSE::8001.  I decipher that as Email address in use.  It makes me wonder if the Google login (that's what I use) timed out or since I log in 3-4 times with different accounts maybe it logs one out.

**Comment by TheFalseKing** [comment]
I seem to get this error every time I log into an account through the live map. Only seems to happen on 1.06. 1.03 I don't seem to get the error. Curious if you get a ECONNECT error sometimes instead of the map loading up.
