### ISSUE TITLE
random disconnection  "Outage"

### ISSUE THREAD

**Issue by tigerwong** [mchristopher/PokemonGo-DesktopMap#522]
anyone experience this issue? after running it for a while it just randomly (I think) has outage?

I am running it on a MAC .

**Comment by tashinasydney** [comment]
I am on Windows 10 and mine does this about once every hour or so. I can't really use it mobile because I can only fix it by closing and re-opening the desktop program. Refresh command does not help.  Would be great to know how to fix, but would also help if it would notify upon outage so I at least know to restart when I'm sitting at the computer but have it running in the background. Thanks. Great to have it work at all though. Caught a few things already that I wouldn't have known about. Brings back the fun of jumping in the car and driving a few blocks to get something.

**Comment by starstremr** [comment]
get teamviewer so you can connect with your phone from where ever you are to restart it

**Comment by tigerwong** [comment]
Hi Starstremr, that is a workaround but not a solution :)

**Comment by Mirx** [comment]
Enable the "toggle developer tools" and check in the console tab what is happening. PTC servers are having issues, so it might just be your session expired (I believe that's around 1400 seconds, but the console states it) and the new session fails to login in.

**Comment by tigerwong** [comment]
thanks. so the issue is with the PTC servers? what is PTC anyway? is that something that you manages or Nintendo?

**Comment by Mirx** [comment]
PTC = Pokemon Trainer Club.

That account is the preferred login method over google, as the google logins time-out after 30 minutes, and you need to restart the map application.

**Comment by tashinasydney** [comment]
Makes sense. I am using a Google login. I will get a PTC login so it's easier for me, and yeah, I should get remote control software for the phone. Never used it so sort of dropped off my apps list. Thanks.

**Comment by tigerwong** [comment]
Wonderful.. that fixes the whole issue :)
