### ISSUE TITLE
Javascript Console Problem

### ISSUE THREAD

**Issue by Deathstroke10** [mchristopher/PokemonGo-DesktopMap#533]
![screen shot 2016-08-02 at 3 08 59 am](https://cloud.githubusercontent.com/assets/20789561/17321597/02b0095e-585f-11e6-9650-7318068dfc9d.png)
I keep getting this message whenever I create an API Browser Key, any solutions?

**Comment by Yashley05** [comment]
I had this problem few minutes ago and managed to solve it, please refer to old posts.

I had this issue several time last night. Did 2 email addresses with several API but nothing worked. In fact it turned out that the API was not Enabled. I just did so and it loads the map.

Go on Google API Console, click on Dashboard, then Enable API, then choose Google Maps JavaScript API (Which I did), then Enable it. 
Log out from Pokemon Go Live Map, paste the API then log in again. It worked for me and hopefully for you too.

**Comment by Deathstroke10** [comment]
It worked!!!! You're awesome, thanks a ton, i appreciate it!!

**Comment by Deathstroke10** [comment]
BTW is there anyway to put the map on your phone?

**Comment by Alframo18** [comment]
What do i do if i enabled it and it still shows the same thing
