### ISSUE TITLE
[Feature Request] Let us define scan radius

### ISSUE THREAD

**Issue by Jagatai** [mchristopher/PokemonGo-DesktopMap#552]
Hello,

the program is running like a charm, i just have one suggestion: Let us define scan radius. 
I live in a rural area, and both my workplace and my home are quite close to the woods. If it was possible to just scan the inner three or four circles, it would keep me up to date on anything that i'm willing to get while also not wasting time on scanning pokemon-free, partially unwalkable woodlands.

**Comment by khashte** [comment]
that's already possible - on the login screen, you can adjust the radius (standard is set to 7). You have to scroll down if you haven't seen it yet. The smaller the radius - the faster the rescan.

**Comment by Jagatai** [comment]
Thank you, i honestly didn't expect to find it there. Soooo, would it be a big problem to add that to the "main" screen?

**Comment by Kazpers** [comment]
I believe the original code on which this is build/is a wrapper does not allow changing the steps parameter during runtime. Whether that's because it's hard/impossible or just not thought of I don't know, but it'd definitely require changing the original codebase, which can add complexity in updating to newer updates. So I don't think you'll see that...

**Comment by AVellucci** [comment]
@Jagatai I've opened a feature issue for this, it might be a nice feature to have.
Please follow #561
