### ISSUE TITLE
Only detecting pokemon with 2m or less until expiration

### ISSUE THREAD

**Issue by blonkpuff** [mchristopher/PokemonGo-DesktopMap#572]
Well for the most part.  Rarely you get pokemon at 11mins plus but 90% of the pokemon popping up have about 2minutes or less and a lot of time 30 seconds and below and it's not enough time to snatch these. Pokevision seemed to grab most of the very recent spawns but this livemap seems to be getting to everything way late.

**Comment by TheFalseKing** [comment]
When they first appear they have 15 minutes before despawning. The reason you have 2minutes is because the pokemon wasn't found until its timer was almost up. The best way to find pokemon quickly is to have a much smaller radius and multiple accounts scanning.

(there is a thread just like this: https://github.com/mchristopher/PokemonGo-DesktopMap/issues/535)

**Comment by blonkpuff** [comment]
I have selected all the basic rares and up (about 50 pokemon) and I'm monitoring the times when each and every one pops into existence on the map. They are almost universally 2mins and below immediately after appearing on the map.  I understand that they can be found when the timer is almost up....but every single time?

**Comment by minim8** [comment]
lure pokemons only last about 3 miniutes. active "Pokestops" "Only Lured" and check

**Comment by blonkpuff** [comment]
Done all that, it doesn't matter what settings are checked, the pokemon returning are 2mish which kinda sucks.  I get from the other thread that you can set up 15 ptc accounts and launch 15 more instances of this app but isn't that kinda lame compared to what pokevision was accomplishing?  I still call this a pretty big issue because who's going to want to go through all that?

**Comment by minim8** [comment]
Please read my post carefully. Changing the Map settings wont change the Pokemon ONLY BEEING THERE FOR 2-3 MINUTES. Niantic makes all lured Pokemons only spawn for 3 minutes and disappear afterwards. If you have "Pokestops" and "Only Lured" activated you can see for yourself/verify, that these 3-min-Pokemons were spawned because of a lure module. So everything works as it should be.

**Comment by blonkpuff** [comment]
Please read my post carefully too. I'm talking about ever pokemon that spawns, lured or otherwise. EVERY pokemon shows up as 2minutes or less, lure or otherwise. Once in a blue moon you get one that catches at 11 minutes or something but lure or no....2m or less. I don't call that working well if you don't even have time to get the thing.

**Comment by minim8** [comment]
Can you maybe provide a screenshot of this with at least 4 Pokemons that are not lured (so have lured pokestops active) and have a timer with less than 3 minutes? 
Even if you have a very high scanning radius the times should in general almost be distributed uniformly. Are you having this issue only with version 0.1.6 or also the earlier ones like 0.1.3?

**Comment by blonkpuff** [comment]
I have my pokemon lists down to the very few I still need and a couple of that I keep up to check that the map is working but here's 3 unlured that popped up just now at really low times. (Like pretty much everything.) It's like the map isn't scanning fast or waiting until the's a low time to list.  I know that's odd but that's where I'm at.  I've never used this program before so 1.6 is my first experience. 

![pokemon](https://cloud.githubusercontent.com/assets/20802361/17346848/a9a8fa7e-58da-11e6-9501-e0d91c88c100.png)

**Comment by musicgreg** [comment]
I am not sure why but I have the same issue with all the versions newer than 1.3 so I have just been using 1.3
