### ISSUE TITLE
Pokemons showing up at area that wasn't scanned.

### ISSUE THREAD

**Issue by jonathanmcc** [mchristopher/PokemonGo-DesktopMap#597]
When I scan, some Pokemons will show up really far away from scan radius with a despawn time of no more than 3 minutes. This is troubling because sometimes it also triggers notifications and I don't even know if it's really there. 

I have tried using other scanning tools to scan those Pokemons and usually nothing shows up. I have also subscribed to a local radio station that announces rare Pokemons that spawn within the region and they have never mentioned any one of those Pokemons outside of scan radius.

Is this a known issue? I am using Windows 10.

![image](https://cloud.githubusercontent.com/assets/1588147/17366136/29f9df36-59bc-11e6-88ac-225d7322ab8e.png)

**Comment by EternisRequiem** [comment]
Turn on pokestops.  Turn on pokestops with lures.  Those have been 100% of those pokemon for me.

**Comment by romanticheart** [comment]
Did you previously search those areas? I've found that mine will occasionally show pokemon in areas I had set up before.

**Comment by zaqrwe** [comment]
I've also noticed that error. It's frustrating, because I can see rare pokemons "nearby" in app, but scanner shows mi f*cking pidgeys far far away instead.. And I checked few pokemons away of my scanned area. It wasn't lured. It it was, it last 2 and half minute, but those pokemon stands for about 13 minutes. 
Btw. Did you notice, that pidgeys and rattatas are always first on map? 

@EternisRequiem I'm searching with lured only pokestops on, it doesn't help.

@romanticheart  And I didn't search in those areas before.


I'd really prefer to see all pokemons close to me, than more of them far away and nothing close :(

**Comment by jonathanmcc** [comment]
@zaqrwe I managed to get to one of those spots before the pokemon disappear (I ran so fast that one of my toe's nail came off). And **YES**, there is actually Pokemon there, and it is next to a PokeStop. But it doesn't have lure around it. So I imagine it was lured but the timer was up.
