### ISSUE TITLE
After clicking "Login wtih Google" errors...

### ISSUE THREAD

**Issue by TroutNemesis** [mchristopher/PokemonGo-DesktopMap#605]
Here is a screenshot...
<img width="678" alt="screen shot 2016-08-03 at 11 22 02 am" src="https://cloud.githubusercontent.com/assets/9247540/17375036/8f64f518-596c-11e6-9429-c8caf38600cf.png">

I'm on Mac el capitan. I also tried on windows 10, but I got the same error message.

Any ideas? 
Thanks!

**Comment by Genek1968** [comment]
I had the same issue. Most of the time the solution is  to enable the Google Java API  from the Google API Console. If it is already enabled then double check if the API key was typed in correctly .  I got this error because the API key was not typed in correctly. ( for some reason I'm unable to paste the API in the login module)
