### ISSUE TITLE
False Pokemon Findings

### ISSUE THREAD

**Issue by JDClough** [mchristopher/PokemonGo-DesktopMap#612]
On multiple occasions, I go out to catch a rare pokemon that the map says is there, but when I arrive at the destination, the Pokemon is not there (Yes, I was within the time frame that the map gave me for the pokemon)

**Comment by minim8** [comment]
Restarted the game when you arrived and waited more than 10 secs? Had this happening to me for a while

**Comment by brianbuquoi** [comment]
I think the time changes they made is causing weird issues.... I had to walk about 20-30 yards further than what is normally a spawn location near work to find things that were showing in that location today... Weird things are happening.

**Comment by rickymiles22** [comment]
Its likely because of the scan radius & scan time changes, the pokemon are there but your device isn't showing them because you have to be in the exact area and wait for the scan to complete.  Sometimes for me I wait 30 seconds or more and nothing shows up but I have 2 devices, a phone & tablet both logged into the same account.  Often the pokemon will show up on one device and not the other or it will show up on one then a minute or more later it will show up..  It's like the scan request every 10 seconds sometimes doesn't go through properly due to network issues.  If the scan time was reduced there would be more chances for the response to go through..  Really weak on Niantic's side to make the request time so high.  Part of it is to screw people like us who are using 3rd party tracking apps but it also screws players on bikes in a major way.  It's impractical to go out on a bike ride as you're travelling too fast for the scan and almost nothing ever shows up unless you're walking now :-/
