### ISSUE TITLE
Someone Please Explain What This Means

### ISSUE THREAD

**Issue by Stevendylan01** [mchristopher/PokemonGo-DesktopMap#640]
https://github.com/keyphact/pgoapi

**Comment by mg6101** [comment]
That is the golden ticket. After 3+ days of working the changes to the API have been cracked. The encryption changes turned out to be pretty significant. However, the developer who created the map portion pulled his code down. Many are creating their own repo of his code and trying to get it back up and running but this program will need to be diverted to use one of those forks instead of the original one. We might be saved after all.

**Comment by pocketq10** [comment]
i cant wait!!!! these guys are the best

**Comment by Stevendylan01** [comment]
Thank you for explaining it lol

**Comment by ejd59005** [comment]
Woot. Cant wait for the update

**Comment by DaRealDfid** [comment]
Oh yeah, I've been waiting for some news Finnaly :D :tada:

**Comment by Ph4i1ur3** [comment]
Niantic will never stop sending these silly cease and desist letters, apparently what they don't realize is they can stop one individual, but they cannot stop us all.

**Comment by Shogunz1** [comment]
Any e.t.a. on the update? Can't wait for it to be back up.

**Comment by earthchie** [comment]
This map just updated!
https://github.com/scottstamp/PokemonGo-Map

**Comment by PokemonCindy** [comment]
What that should means, can somebody actually use that now or? @earthchie

**Comment by earthchie** [comment]
It means we can use this repo instead of AHAAAAAAA's repo

**Comment by TravisMeister** [comment]
Im waiting for an compiled version for windows anyways.

**Comment by SolutionNine** [comment]
@earthchie How do I set that up right now?

**Comment by Aerokii** [comment]
@SolutionNine It seems the creator was sent a cease and desist, so it seems that map has met its end as well.
