### ISSUE TITLE
Ban

### ISSUE THREAD

**Issue by omygod22** [mchristopher/PokemonGo-DesktopMap#66]
I use a different account but same network (ip). Is there a chance to get a ban? I am not very good in programing so I dont know how your app offends the game. So I rather ask about risks :)

**Comment by hassanalami** [comment]
Niantic doesn't ban users, it's just "soft ban" that last some hours and makes pokemons harder to catch

**Comment by omygod22** [comment]
Thank you for answer, but any blue post for your statement?

**Comment by hassanalami** [comment]
No, just read that in many blogs

Le 21 juil. 2016 10:08 AM, "omygod22" <notifications@github.com> a écrit :

Thank you for answer, but any blue post for your statement?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/mchristopher/PokemonGo-DesktopMap/issues/66#issuecomment-234185341>,
or mute the thread

**Comment by jnovack** [comment]
Use at your own risk. (TM)
