### ISSUE TITLE
so it works or not?

### ISSUE THREAD

**Issue by angelo8800** [mchristopher/PokemonGo-DesktopMap#668]
i have the new version i see the map no pokemon gyms or pokestops

**Comment by Shogunz1** [comment]
its working for me

**Comment by Shogunz1** [comment]
atleast on my two accounts

**Comment by PokemonCindy** [comment]
Working for me too :+1:

**Comment by Shogunz1** [comment]
thats funny you say that, on my third it does the same thing. waiting on the top. odd. two work though.

**Comment by Mackiiboy** [comment]
It's working fine for me. Running on 9 different accounts with the same Google API key. In the login-screen, I set a predefined long/lat-coordinate value before logging in. This is my setup (using radius 4 on each account): http://i.imgur.com/FwoVi8i.png

**Comment by ac796** [comment]
Do you use google accounts or ptc accounts?

**Comment by angelo8800** [comment]
i use google acount see nothing

**Comment by Mackiiboy** [comment]
ac796: I'm using only ptc accounts, but the 9th account that I created today did not work at first (my old 8 accounts worked fine). After I logged in on it on my mobile phone and set a nickname, it started to work as well.

**Comment by ac796** [comment]
All of my PTC accounts are waiting. One google account out of 3 is operational. Any tips?

**Comment by PassyFox** [comment]
Mackiiboy how did you enter 9 accounts??? or are you just running the program multiple times?

**Comment by Mackiiboy** [comment]
Yes, I am running the program with multiple instances. To speed up the login, I've made a AHK-script that  enters the username, password, long+latitude-coordinates + API-key automatically for each account, instead of doing it manually.

**Comment by ac796** [comment]
So apparently you now have to go onto Pokemon Go and accept the terms and conditions with your new account to make the PTC account work.

**Comment by TomanPCM** [comment]
wokr :)

**Comment by dacutz3** [comment]
I am still having problem with Loading.. I am stuck at "Please wait, loading..."

**Comment by gonzaloh92** [comment]
@Mackiiboy is that possible on mac?

**Comment by ac796** [comment]
Yes, I run it on mac, works fine now

**Comment by gonzaloh92** [comment]
@ac796 how? Thanks!

**Comment by ac796** [comment]
Just make some PTC accounts, accept the TOC ingame for each, run the app multiple times.

**Comment by gonzaloh92** [comment]
How run the app multiple times? Sorry

**Comment by Ezoteric** [comment]
@Mackiiboy how do you get it all in one map again ? seems its nothing doing that anymore to me :(

Im also interested in the AHK shit :P

**Comment by Mackiiboy** [comment]
@Ezoteric Okey, here is a step by step guide how I did setup everything:

(1) Create n amount of PTC-accounts depending on how large area you want to scan.
(2) Accept the the terms and conditions in game for each account before using them.
(3) Get a Google API-key, guide here: https://github.com/mchristopher/PokemonGo-DesktopMap/wiki/Google-Maps-API:-a-brief-guide-to-your-own-key
(4) Install the latest version of PokemonGo-DesktopMap
(5) Run the Pokemon GO Live Map application via the shortcut, enter the Username, Password, Google Maps Keys and a latitude + longitude to start with (you can get long/lat values here: http://www.mapcoordinates.net/en) and use radius 4 in the scanning options (a scan cycle takes approx 5.5 minutes with radius 4), and then hit Login With PTC. 
(6) Open a new instance of the application and repeat step (5) for each PTC account you have, using the same API Key but different starting coordinates for long/lat. 

The result will be 9 different windows that basically displays the same data since they all are connected to the same database file. 

If it takes much time to find proper long/lat-coordinate values for the other accounts, you can simply calculate them by adding/subtracting these distance offsets (only for radius 4): http://i.imgur.com/DTDBfHu.png ; however, I'm not sure if you can use the same offsets all over the world, maybe they might differ (?).

**Comment by Ezoteric** [comment]
Thnx @Mackiiboy for the super reply, i skipped step 2 btw :P maybe thats a problem.

I have good coors so thats not a problem, the problem is, i dont get all the scanned areas on 1 map anymore :P

**Comment by Ezoteric** [comment]
@Mackiiboy Yes is there anywhere we can chat that would be very helpfull :)

**Comment by Mackiiboy** [comment]
@Ezoteric The script is hard coded, so you will have to customize it on your own, but the language is pretty simple to understand, so it should not be a problem. Here are some steps you have to follow:

(1) Download AHK installer:
https://autohotkey.com/download/ahk-install.exe
(2) Download my template AHK-script:
https://www.dropbox.com/s/mwfzwhegb83i1fn/pokemongo.ahk?dl=0
(3) Right click on it and edit script. You will have to edit 5 variable values in the script; first an object with all account names, then the password you are using (if different passwords, you have to create an object for this as well), the API-key and two objects with all lat/long coordinates.
(4) Save the file and run it.
(5) Open an instance of Pokemon GO Live Map and press the Ins (insert key) on your keyboard. The script will then insert all data that is necessary and login. 
(6) Do step (5) again until you have logged in on all your accounts. (In the future, I will make the script do this automatically for all accounts so you won't have to manually press Ins for each login)
(7) Press the End key on your keyboard  and the script will terminate.  

If you have any questions, feel free to ask me.

**Comment by Ezoteric** [comment]
@Mackiiboy thnx man much appriciated

**Comment by gonzaloh92** [comment]
Thanks! But How do you open multiple instances?

**Comment by Mackiiboy** [comment]
@gonzaloh92 You just start the application via the shortcut and it will open a new instance of it, use the shortcut again and you have another instance.  If you do not have a shortcut and are running on Windows, you can create a new shortcut, but make sure it has the target C:\Users\YOUR_USER_NAME\AppData\Local\pokemon\Update.exe --processStart "Pokemon GO Live Map.exe" and that is starts in C:\Users\YOUR_USER_NAME\AppData\Local\pokemon\app-0.2.1
also replace "YOUR_USER_NAME" with your user name above.

**Comment by gonzaloh92** [comment]
I'm on mac.
