### ISSUE TITLE
Export all coordinates to spreadsheet

### ISSUE THREAD

**Issue by jonnyjules** [mchristopher/PokemonGo-DesktopMap#710]
How can we get a list of coordinates to export to spreadsheet? Thank you!

**Comment by pill0ws** [comment]
I'd like this too, primarily because spawn locations seem to be static although not always populated. I logged as many as I could before the first API change. I would love to just know where things are at in general before they pull the rug out from under us again. Even just some kind of event log in general, although that may already be a thing that my noobish scrub brain has no idea how to access.

**Comment by dudeunit** [comment]
I would like to support this request. This map probably won't last forever and i'd like to know where to start looking if i'm without my trusty treasure map.... But i'm also just a sucker for patterns :-)
Format is irrelevant, conversion is always possible.

So in short... Pretty please?
And thank you for the map!
