### ISSUE TITLE
No rescan Map

### ISSUE THREAD

**Issue by ShaguaRs** [mchristopher/PokemonGo-DesktopMap#711]
When Scanner end scan radius, don't rescan it again to find new pokemon. Just at end, do nothing and i must close program i run again.

**Comment by Anden1980** [comment]
Same problem

**Comment by ShaguaRs** [comment]
I left program and go do something else. It rescan but after 20-30 minutes.
There's some way to change this ?

**Comment by krummrey** [comment]
You're probably scanning an area that's too large. Anything over 5 or 6 is probably too large to catch them in time.

**Comment by ShaguaRs** [comment]
So u mean u would set scan arean on 3-4 ?

**Comment by Regulator69** [comment]
^^ yes, if its just a lil town especially, 4 more than covers it, 3 would be fine but there is a spawn in the 4 range that can spawn some rares that i like to check on.. 4 would be the circle in the center then 3 more full rings around the center one however many that takes.. and if you have certain spots you like to check on.. switch your settings to follow your location, and just move the pointer to where you wanna scan and it will scan that spot, then starts circling around that circle again starting all over again instead of finishing however many rings of circles you had preset.. if any of that makes sense to ya lol

**Comment by mg6101** [comment]
You can open a second instance of the map and login with a different PTC account (be sure to complete the tutorial on the new account). Then minimize the second instance and both will populate on the first map. This way you can scan a 5 radius if you open the second instance 5 minutes after the first.
