### ISSUE TITLE
is it possible to change the refresh speed?

### ISSUE THREAD

**Issue by jesperkv** [mchristopher/PokemonGo-DesktopMap#715]
i find it pretty annoying. thanks in advance

**Comment by mg6101** [comment]
No. Any scanning speed faster than roughly 10 seconds gets dropped by the server and you will see 0 Pokemon show up. Solution is to open a second instance of the map and login with a different PTC account and then minimize it. This will trigger both instances to populate on the first map. You just need to start the second one an appropriate amount of time after the first (i.e. 5 minutes). You can string as many of these together as you want so long as they are different accounts for each one. Remember to login with each account and complete the tutorial otherwise that account isn't active and API calls will be dropped. Id suggest using an old phone if possible just to be sure.
