### ISSUE TITLE
Error on relogin with server mode enabled.

### ISSUE THREAD

**Issue by chun1324** [mchristopher/PokemonGo-DesktopMap#740]
Steps: 
1. Login with PTC, with server mode enabled
2. Logout
3. Login with PTC again, with server mode enabled
[Error Message Here](http://imgur.com/a/4JWg1)

So far it is okay to continue by restarting the application.

**Comment by KrogerKandy** [comment]
This error has been reported multiple times as it's being encountered in different ways. So far I haven't seen an acknowledgment of the problem or anything. Since this error I've been getting all kinds of other errors and it seems to be getting progressively worse. A confirmation that the particular error being reported here is being looked at, would be comforting.
