### ISSUE TITLE
How to Run Multiple .exe and how to customize configuration of .exe???

### ISSUE THREAD

**Issue by dudeman999** [mchristopher/PokemonGo-DesktopMap#743]
The earlier versions of this scanner wasn't compiled into one exe file which allowed for customization of the step distance, scan delay, and number of threads? How can we customize these options now for the exe and why did he compile it to an exe for windows in the first place????

And how does one now run multiple instances of the exe on one windows screen??? When i try to open a second window, the first one exits and reopens...

**Comment by azertion** [comment]
I'm interested in this too. More specifically I'd like to run multiple instances (with their own accounts or not) and have the **results joined into a single map**. This because the scan interval of 10 seconds (why is that btw..?) makes a full scan of distance 5 take about 10 minutes, Which means new pokemon could be off in about 3 minutes.

Even more interesting would be to be able to make a **list of specific areas to scan**, as spawning locations seem to be fixed. I know the spawning locations around me and i want to scan those, without all the known deadzones in between them. It takes a bit of preparation work, but saves about 50% of scan-time.

**Comment by RedHerring27** [comment]
You are able to run multiple instances by running the .exe more than once and logging in with a different account. All the scans will show up on the same map. However, this process is tedious and I would like to see it implemented as a feature where the program remembers multiple accounts and their locations. @dudeman999 It sounds like you're running the installer when you're restarting the program. It should have generated a shortcut to a .exe on your desktop. You can run multiple instances from that.

**Comment by mike2246** [comment]
Having trouble running more than 2 instances, the 3rd one runs but just says waiting. Using a different PTC account for all 3

**Comment by RedHerring27** [comment]
When you create a new Pokemon Go account you have to accept the in-game terms of service . Until you do that it won't work in the scanner. Just open the account in the Pokemon Go app and accept the term of service. Then it should work fine.
