### ISSUE TITLE
Stop scanning after few hours 

### ISSUE THREAD

**Issue by sweebee** [mchristopher/PokemonGo-DesktopMap#758]
The app stops working after around 2-3 hours. I have to restart it to get it working again.

**Comment by rynsey** [comment]
Yup.  Me too.

**Comment by nicholasgodoyx** [comment]
Mine does it more often than that.

**Comment by Clavus** [comment]
I've got the same issue, but noticed you don't even have to restart. When you reset the search by dragging the location marker for example, it starts scanning again right away.

**Comment by rynsey** [comment]
I've tried inputting a new location but it doesn't restart.

**Comment by MrAwesomers** [comment]
Are you guys using a PTC account or a google account for scanning? Just asking because Google accounts stop after a certain time. I haven't tried the scanner after the API change yet, so there might be an other reason it stops scanning. Try to refresh when it happens. To refresh, use cmd+R on Mac OS X or ctrl+R on Windows. Or you can select it from the menu in the app.

**Comment by rynsey** [comment]
I'm using Google however it always stops working when I'm using mobile and can't refresh. 

--Lynsey

**Comment by kingavneet** [comment]
If you are using a google account then switch to PTC...make a new PTC account. I have great success doing that

**Comment by sweebee** [comment]
Logged in with a club account. Lets se what happens.

**Comment by sweebee** [comment]
Still running! So use a Pokémon club account.
