### ISSUE TITLE
Am I missing something? help

### ISSUE THREAD

**Issue by Arepas** [mchristopher/PokemonGo-DesktopMap#770]
Hi anyone can give a hand I'm no getting pokemon, pokestops, or gyms in map 
I'm using a new PTC acount, accepted ToS in game and settup the API for javascript for google map in google console and still nothing :(

pokemon, gyms and pokestops arent hidden in settings

main.html:168 2016-08-08 23:16:09,904 [ search_worker_0][        search][    INFO] Search step 4 beginning (queue size is 15)
main.html:168 2016-08-08 23:16:09,904 [ search_worker_0][      auth_ptc][    INFO] PTC User Login for: **ACOUNT**
**main.html:274 MAP: Uncaught TypeError: Cannot read property 'style' of null**
main.html:168 2016-08-08 23:16:10,523 [ search_worker_0][      auth_ptc][    INFO] PTC User Login successful.
2016-08-08 23:16:10,523 [ search_worker_0][      auth_ptc][    INFO] Request PTC Access Token...
main.html:168 2016-08-08 23:16:10,648 [ search_worker_0][      auth_ptc][    INFO] PTC Access Token successfully retrieved.
main.html:168 2016-08-08 23:16:10,680 [ search_worker_0][        pgoapi][    INFO] Creating a new direct request...
2016-08-08 23:16:10,680 [ search_worker_0][        pgoapi][    INFO] Adding 'GET_MAP_OBJECTS' to RPC request including arguments
2016-08-08 23:16:10,680 [ search_worker_0][        pgoapi][    INFO] Execution of RPC
**main.html:274 MAP: Uncaught TypeError: Cannot read property 'style' of null**
main.html:168 2016-08-08 23:16:11,049 [ search_worker_0][        pgoapi][    INFO] Cleanup of request!
main.html:168 2016-08-08 23:16:11,049 [ search_worker_0][        models][    **INFO] Upserted 0** **pokemon, 0 pokestops, and 0 gyms**
**13main.html:274 MAP: Uncaught TypeError: Cannot read property 'style' of null**

and getting this in console

![nothing](https://cloud.githubusercontent.com/assets/20797937/17503578/d313b50a-5da5-11e6-8399-5c6eb58b34c2.png)

**Comment by ohiotech** [comment]
Though there may be more reasons, I've seen this for 1) Logging into the game and to the console with the same account. If you're logging into the game with the same account you're using here, you've got a chance of getting banned faster with that account 2) You have more than one map open with the same credentials.

In short, use one set of credentials for the game and one for the map.

**Comment by pill0ws** [comment]
I seem to notice odd behavior when signing in with 2 devices if I am driving around (same account logged in with both). at some point pokemon seem to stop appearing on either device. This could possibly be related to whatever security measures have been put in since the last patch. I notice an effect immediately upon signing in with the second device even while stationary (only one device will trigger pokemon discoveries at the same location). Once I start moving fast thats when both devices 'seem' to be effected, an at some point, barely anything at all seems to trigger. When I only log in with one device, this doesn't occur at all and everything appears normally. I'd follow Ohiotech's solution and honestly, I wouldn't try logging in with tons of separate accounts to scan multiple areas anymore either. These are the things that were causing the most server strain and if they indeed made it impossible to play the game normally using two devices simultaneously then I wouldn't put it past them to be trying to stop multi logins as well.  A single scanner login is likely going to be much harder to detect than 4 (even with different API's and different accounts, if they're all on the same IP and all repeatedly searching the exact same coords surely botlike activity is detectable in some way.)

**Comment by cybernimf** [comment]
Excellent idea on logging in 2 different accounts, I had not thought of that, but did make a new ptc one yesterday. Thank you :)
