### ISSUE TITLE
Slow Scan Speed?!

### ISSUE THREAD

**Issue by Hidden999** [mchristopher/PokemonGo-DesktopMap#790]
Why is the speed of the scanning so much lower. It is even lower than first without the speedboost?!

**Comment by dudeman999** [comment]
You need to follow all thats been happening bud.... The Game itself updated and changed the API and pokemon refresh rate to updating every 10 seconds.... which means the scanning maps only update every 10 seconds.... which is why it is slower.....

The refresh speed used to be like 5 seconds a while back,
