### ISSUE TITLE
Location is "fixed" on MacOS

### ISSUE THREAD

**Issue by alessandrocasciaro** [mchristopher/PokemonGo-DesktopMap#8]
I "refresh" the location but the app still remain on the previous settings.

**Comment by SebCorbin** [comment]
Same here

**Comment by harrynoob** [comment]
I've got a sort-of-but-improper fix. In [example.py](https://github.com/mchristopher/PokemonGo-Map/blob/master/example.py) in `main`, one should replace

`
    for step in range(steplimit2):
        #starting at 0 index
        debug('looping: step {} of {}'.format((step+1), steplimit**2))
        #debug('steplimit: {} x: {} y: {} pos: {} dx: {} dy {}'.format(steplimit2, x, y, pos, dx, dy))
        # Scan location math
        if -steplimit2 / 2 < x <= steplimit2 / 2 and -steplimit2 / 2 < y <= steplimit2 / 2:
             set_location_coords(x * 0.0025 + origin_lat, y * 0.0025 + origin_lon, 0)
`
by

`
    start_lat = FLOAT_LAT
    start_long = FLOAT_LONG
    for step in range(steplimit2):
        #starting at 0 index
        debug('looping: step {} of {}'.format((step+1), steplimit**2))
        #debug('steplimit: {} x: {} y: {} pos: {} dx: {} dy {}'.format(steplimit2, x, y, pos, dx, dy))
        # Scan location math
        if -steplimit2 / 2 < x <= steplimit2 / 2 and -steplimit2 / 2 < y <= steplimit2 / 2:
             set_location_coords(x * 0.0025 + start_lat, y * 0.0025 + start_long, 0)
`
(the main change here is in the `set_location_coords` call)
This causes the backend to search around the last selected location (using the Set button) instead of the original location, but only for one iteration of the search.

**Comment by simonwicks** [comment]
This is the closest bug I could find to a suggestion I have, (although I'm also having this problem of the pin not updating). How hard would it be to implement a move pin option, rather than having to type in the coordinates? (paste also doesn't work here, or in login, which makes it hard for us with strong passwords!  I'll make a bug report on that one seperate)
