### ISSUE TITLE
Multiple Account Set-Up

### ISSUE THREAD

**Issue by BMWtx** [mchristopher/PokemonGo-DesktopMap#823]
I and many others seem to be out of our depth on this one -- I've been searching for a "how-to" of sorts but it seems that most instructions are referenced assuming some foundation knowledge which I admittedly lack. I will literally paypal $20 to the first person who can write a dummy's guide equivalent to help me solve this issue. 

Alternatively: if you're in the Houston area, the only remaining true Dratini nest around.

**Comment by ntomec** [comment]
If what you're trying to do is set up multiple accounts in order to scan multiple locations at once then what you need to do is have multiple occurrences of the application running at the same time. On a PC i believe you just need to hold shift and left click on the application. If you're using a mac you can do this by opening terminal and entering    

open  -n -a "Pokemon GO Live Map"

and a second window of the map will open, and use a different gmail account or PTC account to log in to that one. if you show scanned locations on either of the maps you will see that both areas are being scanned. Hope this is what you were asking

**Comment by long-horse** [comment]
@BMWtx Are you wanting to add a second account so it searches a larger area faster or so you can search another area altogether? @ntomec's suggestion worked for me although not my end goal which is having more accounts in the same window scanning one area faster (3 accounts to scan 3 green circles at a time instead of 1).

**Comment by MrAwesomers** [comment]
A 7 radius scan takes about 15 minutes so just launch a new instance of the scanner every 5 minutes and log in with 3 different accounts. Target the exact same location and it will update 3 times as fast. There probably is a way to automate this process, like a batch file, but I can't help you with that.

As far as I know, there is no way to increase the scan speed since Niantic changed things, forcing the removal of the 'fast scan' option.

**Comment by Roadrunnerjr** [comment]
@BMWtx Where is the last dratini nest in Houston?

_Alternatively: if you're in the Houston area, the only remaining true Dratini nest around._

**Comment by Pixtr** [comment]
Hey guy, can anybody help me how to open second instance of the program on Windows so I can scan with multiple accounts? When I start the application again, it closes the first instance...

Thank you
