### ISSUE TITLE
Possible reason for stuck at Loading

### ISSUE THREAD

**Issue by Heinyy** [mchristopher/PokemonGo-DesktopMap#836]
It will be possible to choose the path of installation. PokemonGo-DesktopMap dont seems to love àçâèéô as seen here https://cloud.githubusercontent.com/assets/1179744/17565420/636089a2-5f05-11e6-82f1-847ee32a32e8.png

**Comment by sokalbr** [comment]
I had the same problem because it could not find the livrairie .

After searching on the disk c :, it appears that the requested library is located here:
C: \ Program Files (x86) \ Trend Micro \ OfficeScan Client \ Suspect

So this is the antivirus that has been a problem .

After having copied / pasted the DLL in the appropriate directory , it works !!!
