### ISSUE TITLE
Javascript error on windows realease

### ISSUE THREAD

**Issue by herculys** [mchristopher/PokemonGo-DesktopMap#842]
![1](https://cloud.githubusercontent.com/assets/8635798/17586143/38289fea-5f96-11e6-8cb0-1c1db37e4286.jpg)

**Comment by Heinyy** [comment]
You can ignore

**Comment by galaxy9999** [comment]
I got this error on some workers not all. I don't know if it related. hut it may cause scan location (your pinned center location)  change due to this kind of error. I have seen this happen a lot, Accounts with such error whose scan location will switch to previous logged in acct. or default location at your PC location. Do anybody else see this kind of pattern.
