### ISSUE TITLE
Too many connections! On mobile. Any way to fix this message?

### ISSUE THREAD

**Issue by selfdisplaced** [mchristopher/PokemonGo-DesktopMap#878]
Too many connections! The tunnel session '8ab30ad691f1f00459c1fd61224fc6bf' has violated the rate-limit policy of 20 connections per minute. Please decrease your inbound connection volume or upgrade to a paid plan for additional capacity. ERR_NGROK_702

**Comment by bwl7sju** [comment]
If you logout and re-login, the app will work again on mobile. It's not ideal.

**Comment by selfdisplaced** [comment]
if you log in and out again, doesn't it change your address for the mobile?  that's all fine, except it's not easy to navigate to a new address when you are out and about.

TeamViewer doesn't copy to the clipboard of iphone on mobile like it does on PC.

**Comment by gonjiak** [comment]
just refresh the site after a minute or two and it will work again

**Comment by dhyde79** [comment]
this is a bit of a headache....I'd love it if it gave me an ability to just link direct since I already run a couple servers off of the box I run the scanner on...it'd be pretty simple to just launch a browser and point it to (myserver.com):(required port number for this app) and have it work correctly from a browser based on bandwidth and connectivity to my own machine instead of having to go through a third party....

**Comment by torantal** [comment]
Then just rdp to your server and view the map?
