### ISSUE TITLE
After login, the app just shows "Waiting" and doesn't scan

### ISSUE THREAD

**Issue by joshuacane** [mchristopher/PokemonGo-DesktopMap#886]
I never changed any settings, and the app stopped working out of nowhere. I tried making a different gmail and even made a PTC account, but it didn't fix the issue. The app shows lured pokéstops and gyms, but nothing else. I have the scanned locations filter on, but the green circles never appear.

**Comment by primius** [comment]
Since yesterday i have the same problem. Console shows following messages:

2016-08-13 11:31:04,844 [ search_worker_0][        pgoapi][    INFO] Cleanup of request!
main.html:168 2016-08-13 11:31:04,846 [ search_worker_0][        search][   ERROR] Search step 2 map parsing failed, retyring request in 50 seconds
main.html:168 2016-08-13 11:31:54,848 [ search_worker_0][        search][   ERROR] Search step 2 went over max scan_retires; abandoning
main.html:168 2016-08-13 11:32:04,848 [ search_worker_0][        search][    INFO] Search step 3 beginning (queue size is 58)
main.html:168 2016-08-13 11:32:04,882 [ search_worker_0][        pgoapi][    INFO] Creating a new direct request...
2016-08-13 11:32:04,882 [ search_worker_0][        pgoapi][    INFO] Adding 'GET_MAP_OBJECTS' to RPC request including arguments
main.html:168 2016-08-13 11:32:04,884 [ search_worker_0][        pgoapi][    INFO] Execution of RPC
main.html:168 2016-08-13 11:32:05,266 [ search_worker_0][        pgoapi][    INFO] Cleanup of request!
main.html:168 2016-08-13 11:32:05,269 [ search_worker_0][        search][   ERROR] Search step 3 map parsing failed, retyring request in 10 seconds
main.html:168 2016-08-13 11:32:15,308 [ search_worker_0][        pgoapi][    INFO] Creating a new direct request...
main.html:168 2016-08-13 11:32:15,308 [ search_worker_0][        pgoapi][    INFO] Adding 'GET_MAP_OBJECTS' to RPC request including arguments
main.html:168 2016-08-13 11:32:15,309 [ search_worker_0][        pgoapi][    INFO] Execution of RPC
main.html:168 2016-08-13 11:32:15,660 [ search_worker_0][        pgoapi][    INFO] Cleanup of request!
main.html:168 2016-08-13 11:32:15,664 [ search_worker_0][        search][   ERROR] Search step 3 map parsing failed, retyring request in 20 seconds
main.html:168 2016-08-13 11:32:35,697 [ search_worker_0][        pgoapi][    INFO] Creating a new direct request...
main.html:168 2016-08-13 11:32:35,697 [ search_worker_0][        pgoapi][    INFO] Adding 'GET_MAP_OBJECTS' to RPC request including arguments
2016-08-13 11:32:35,698 [ search_worker_0][        pgoapi][    INFO] Execution of RPC
main.html:168 2016-08-13 11:32:36,131 [ search_worker_0][        pgoapi][    INFO] Cleanup of request!
main.html:168 2016-08-13 11:32:36,134 [ search_worker_0][        search][   ERROR] Search step 3 map parsing failed, retyring request in 30 seconds
main.html:168 2016-08-13 11:33:06,170 [ search_worker_0][        pgoapi][    INFO] Creating a new direct request...
main.html:168 2016-08-13 11:33:06,170 [ search_worker_0][        pgoapi][    INFO] Adding 'GET_MAP_OBJECTS' to RPC request including arguments
main.html:168 2016-08-13 11:33:06,171 [ search_worker_0][        pgoapi][    INFO] Execution of RPC
main.html:168 2016-08-13 11:33:06,621 [ search_worker_0][        pgoapi][    INFO] Cleanup of request!
2016-08-13 11:33:06,624 [ search_worker_0][        search][   ERROR] Search step 3 map parsing failed, retyring request in 40 seconds
main.html:168 2016-08-13 11:33:46,657 [ search_worker_0][        pgoapi][    INFO] Creating a new direct request...
main.html:168 2016-08-13 11:33:46,657 [ search_worker_0][        pgoapi][    INFO] Adding 'GET_MAP_OBJECTS' to RPC request including arguments
2016-08-13 11:33:46,658 [ search_worker_0][        pgoapi][    INFO] Execution of RPC
main.html:168 2016-08-13 11:33:47,153 [ search_worker_0][        pgoapi][    INFO] Cleanup of request!
main.html:168 2016-08-13 11:33:47,155 [ search_worker_0][        search][   ERROR] Search step 3 map parsing failed, retyring request in 50 seconds
main.html:168 2016-08-13 11:34:37,158 [ search_worker_0][        search][   ERROR] Search step 3 went over max scan_retires; abandoning
main.html:168 2016-08-13 11:34:47,161 [ search_worker_0][        search][    INFO] Search step 4 beginning (queue size is 57)
main.html:168 2016-08-13 11:34:47,190 [ search_worker_0][        pgoapi][    INFO] Creating a new direct request...
main.html:168 2016-08-13 11:34:47,190 [ search_worker_0][        pgoapi][    INFO] Adding 'GET_MAP_OBJECTS' to RPC request including arguments
main.html:168 2016-08-13 11:34:47,190 [ search_worker_0][        pgoapi][    INFO] Execution of RPC
main.html:168 2016-08-13 11:34:47,545 [ search_worker_0][        pgoapi][    INFO] Cleanup of request!
main.html:168 2016-08-13 11:34:47,548 [ search_worker_0][        search][   ERROR] Search step 4 map parsing failed, retyring request in 10 seconds
main.html:168 2016-08-13 11:34:57,579 [ search_worker_0][        pgoapi][    INFO] Creating a new direct request...
main.html:168 2016-08-13 11:34:57,596 [ search_worker_0][        pgoapi][    INFO] Adding 'GET_MAP_OBJECTS' to RPC request including arguments
main.html:168 2016-08-13 11:34:57,598 [ search_worker_0][        pgoapi][    INFO] Execution of RPC
main.html:168 2016-08-13 11:34:57,940 [ search_worker_0][        pgoapi][    INFO] Cleanup of request!
main.html:168 2016-08-13 11:34:57,944 [ search_worker_0][        search][   ERROR] Search step 4 map parsing failed, retyring request in 20 seconds
main.html:168 2016-08-13 11:35:17,979 [ search_worker_0][        pgoapi][    INFO] Creating a new direct request...
main.html:168 2016-08-13 11:35:17,979 [ search_worker_0][        pgoapi][    INFO] Adding 'GET_MAP_OBJECTS' to RPC request including arguments
main.html:168 2016-08-13 11:35:17,980 [ search_worker_0][        pgoapi][    INFO] Execution of RPC
main.html:168 2016-08-13 11:35:18,332 [ search_worker_0][        pgoapi][    INFO] Cleanup of request!
main.html:168 2016-08-13 11:35:18,335 [ search_worker_0][        search][   ERROR] Search step 4 map parsing failed, retyring request in 30 seconds

**Comment by avogabo** [comment]
login first on pokemon go app to accept terms and then try it

**Comment by primius** [comment]
Ok, that works for me. Maybe my first PTC account has been banned. But i created a 2nd one and after logging into the app and accepting the terms it works now again.
Thanks.

**Comment by joshuacane** [comment]
@avogabo Thank you so much! It's finally working!

**Comment by glurph** [comment]
@primius 

>Maybe my first PTC account has been banned

I think it's likely.  My PTC account seems banned too.

**Comment by francisalfanta** [comment]
I have the same issue:

Console log
2016-08-13 17:31:23,963 [ search_worker_0][        search][   ERROR] Search step 3 went over max scan_retires; abandoning

18main.html:274 MAP: Uncaught TypeError: Cannot read property 'style' of null

**Comment by cooler67** [comment]
That worked! thanks
