### ISSUE TITLE
Unlimited expire time

### ISSUE THREAD

**Issue by Zayonx** [mchristopher/PokemonGo-DesktopMap#899]
Please fix this issues ;( 
![screenshot_12](https://cloud.githubusercontent.com/assets/21014461/17646035/d23721a0-61b8-11e6-9a21-96f46e44bec3.png)

**Comment by NickIxo** [comment]
I have to say if this was implemented by Niantic, rather than a bug, to mess with people who are scanning, it's a genius idea.

**Comment by torantal** [comment]
Please read the existing issues before posting old news.

https://github.com/mchristopher/PokemonGo-DesktopMap/issues/892

**Comment by obuglas** [comment]
Just press on the pokemon with long expired time and "delete"

![image](https://cloud.githubusercontent.com/assets/21020107/17648427/b43e5f1e-621d-11e6-92b1-ecd353604b0f.png)

**Comment by alangerow** [comment]
Remove doesn't work long term. They still show up on each new mobile instance, and if you restart the application. Remove is not a viable workaround.

**Comment by alangerow** [comment]
I'm now showing stacks of Pokemon now with 552 hours until expiration that don't stay gone. I remove them but they return on mobile and when I restart the application.

![image](https://cloud.githubusercontent.com/assets/20896440/17649715/bc0eaf20-61f8-11e6-839c-08301978a531.png)

This has been fixed in the main application, is there any time frame on when the fixes are going to be implemented in this project? Particularly commit #595:

https://github.com/PokemonGoMap/PokemonGo-Map/commit/0f19c0a85b421a83c5c0d50c6fd39d59c1040f2c

**Comment by tranquillian** [comment]
Please could someone let me know if the fix for the expiration time will be implemented into the electron app for mac/windows? I'm not versed in coding/programming but very grateful for this scanner. I am fairly tech minded despite being a noob with python currently so if it's not going to be implemented into the UI wrapper some pointers on how to learn how to implement the fix myself would be great.
