### ISSUE TITLE
Not able to adjust search range or search for location

### ISSUE THREAD

**Issue by MearWolf** [mchristopher/PokemonGo-DesktopMap#9]
This is more of a feature request.
Can you please add the ability to adjust the search range and do a location search via name such as "Street, Town, Country".

PokemonGo-Map already has this functionality

**Comment by shejk0** [comment]
Would also like option to hide pokes.

**Comment by djofwarr** [comment]
1. Got to **PokemonGoMap-Win\resources\app** folder, 
2. **open the main.js** file. 
3. **On line 92 or search for step-limit**, 
The number under step limit is the search radius in kilometers. If you're walking around, anything over 10 is pointless because, by the time you get to the location, the Pokemon would be gone.

**Comment by ilikesomething** [comment]
@shejk0 for the moment you can just delete the file of pokémons you don't want to see ;
go to : \resources\app\map\static\icons
