### ISSUE TITLE
Can I change port number??

### ISSUE THREAD

**Issue by bungasnail** [mchristopher/PokemonGo-DesktopMap#901]
I'm using PokemonGoMap-Win.exe on windows7.
I would like to oparate by change the port number.
What can i doing it ?

**Comment by dhyde79** [comment]
is this an attempt to be able to run the "mobile" connection direct from your PC instead of through the "tunnel" that's built in (and randomly locks you out because "it's had too many incoming connections")?  if so, good lord, I'd love to be able to do that....how about some documentation on that too?

**Comment by nahga** [comment]
This can done already as is(NOT changing the port though). If you are running the map application now, it's already running on port 8001, if you forward that port thru your router to the computer running it, and allow that app/port in your OS firewall, then you can see it directly without using the ngrok tunnel. You don't even need to 'enable' the mobile mode as all that does it fire off the ngrok binary and create the tunnel.

**Comment by dhyde79** [comment]
^ fantastic! that was exactly what I wanted...

bungasnail: there's no need to change port numbers on the app itself, do it with your router when you're forwarding the port.  For example, when you set up the forwarding, I forwarded TCP and UDP (since I don't know which it wants) from port "80" to "8001" so that all I have to do is go into a browser and type in my dynamic dns address and bam, the site pops right up...(ok, not entirely true, I picked an arbitrary port number, checked to see that nothing else uses that port number typically, and then did that, so that the URL is http://my.dynamic.dns:portnumber and it goes straight to it...now, I can pop into the server via teamviewer, launch the app, and as soon as it logs in successfully, I close out of TV, launch the browser on my phone, and load the link....nice and silky smooth...
