### ISSUE TITLE
Pre and post API update accounts

### ISSUE THREAD

**Issue by EAminy** [mchristopher/PokemonGo-DesktopMap#908]
Hello!
Not sure if this has been reported, but I seem to have an issue with PTC accounts created before and after the API update. In total I have 7 accounts, 4 from before the update and 3 from after. The 4 from before the update work perfectly and scans whatever I want. The 3 accounts I created after the update do not scan at all. The button with the status of scanner never switches from "Waiting" to "Operational". All of the accounts have a verified email and work on their website.

Otherwise it is a brilliant program you have made. Works very well and has almost all features one could wish for. The only thing I feel is missing is the ability to log in with multiple accounts in a single instance and an elapsed time clock.

Keep up the amazing work and thanks for making PoGo enjoyable!

**Comment by EAminy** [comment]
Never mind, apparently I had to log in on the PoGo app with the 3 new accounts, something I didn't need to do with the 4 old accounts.

**Comment by EAminy** [comment]
Oh, and an indication of how long the scan would take for each scanning range would be great. Like a 1 range gives a scanning time of 10 sec, 2 range gives 70 sec, 3 give 190 sec and so on. I think it's something like 10+60*(n-1) seconds if n is the range.

**Comment by EAminy** [comment]
Oh and an indicator of how long a scan will take for each range for would be great.

**Comment by abnmojo** [comment]
Just an FYI, I set the scan radius to '5' and put it on the walmart shopping center area about a 2 minute drive from my house and set alerts.  Any more radius than that, it spends too much time scanning the 'edges' of the area and the interior scans will indicate with too little time to run down there and catch anything I need.  about 10 minutes to complete a "5" radius scan of the area, and Walmart shopping center has spawned EVERYTHING I have except a dratini in the past week.  Zero pokestops in the area as well, and it seems ultra rare and rare are on a cycle, 4-5 pikachu a day for a day then none for a day, as are the other rares.  I'm up to 116 of them atm and 90% have spawned there at least once.  Good luck

**Comment by EAminy** [comment]
I know, but if you use 6 accounts and scan an 9 range area you can have each scan-circle scannned every 6 minutes. You do have to manually space the scans apart but otherwise it works great. I can cover all of central Malmö (Sweden). Last week I caught 7 dratinis in 1 hour.

**Comment by Actualgo** [comment]
EAminy, can you explain that a little closer, id like to try that also.  are you running all 6 on the same computer and how ?  and how are you setting up your overlap with a scan range of 9 you need to overlap your scans and time them ?

**Comment by Actualgo** [comment]
and can you get them all to show up on the same webpage  ?

**Comment by EAminy** [comment]
Ok, so if I want to scan a 9 range area I choose a central location and start scanning it. Six minutes later, I open another window of the program on the same computer (with a different account) at the same location. That way the second scanner scans the same circles as the first scanner, it's just 6 minutes behind. I do that with the remaining 4 scanners. This way the scanners should be perfectly in sync so that a scanner is each scan-circle once every 6 minutes. Since each window of the program displays the scans of all 6 scanners, you get a complete map that updates very regularly.

If you wonder why specifically 6 minutes and 6 scanners for 9 range, I did some maths for that. Since it takes 10 seconds to scan each scan-circle, 6 scan-circles equal a minute. The amount of circles in each ring follow the formula 1+6*(n-1), where n is the number of the ring. So the first ring has 1 circle in it, the second has 6, the third 12, and so on. If you add these together, 1+6+12 = 19, you get the amount of circles in a 3 range area. Divide that by 6 to get how many minutes it takes, 19/6 = 3. So a 3 range area takes about 3 minutes to scan. If you do the same thing for a 9 range area, the total amount of circles is 217. 217/6 = 36, it takes 36 minutes to scan a 9 range area. But 36 is nicely divisible by 6, so if I put 6 scanners on it and space them apart by 36/6 = 6 minutes, they should be equally distributed.

If you do not know what I mean by scan-circles, turn on the "Scanned Locations" option and you'll understand.

**Comment by EAminy** [comment]
Just to clarify, the showing up on the same webpage happens automatically. The scanners share their information with each other.

**Comment by EAminy** [comment]
For the timing, I find it easier to just find the circle the scanners should reach

**Comment by EAminy** [comment]
Sorry, pressed the wrong button.

**Comment by jijetelu** [comment]
Any new info about those post API accounts, I am having the same problem.

**Comment by EAminy** [comment]
Just log in with the accounts that do not work on the app and catch one of the starters. Then it should work.

**Comment by jijetelu** [comment]
Well, I already did that a couple of days ago. The problem stared today and I cannot login to that acounts on the app.

**Comment by pill0ws** [comment]
I had that problem as well, I actually created a brand new account. The previous accout appears to be frozen though not yet banned. I can login to PTC with it but cannot change any settings at all and cannot use my silly PTC coins I got free when starting the account to buy frivlous items from their shop either. It appears the account is likely up for review or something like that. IT just suddenly stopped the night before the sticky timers started. I'm trying to be extra careful in how I use the App with the new one, running only one instance and just hanging out in the area it is scanning; Moving it around manually or by just driving with "Follow Current Location" toggled on. Then toggling it off when I see something cool in the scanner (it gave me an idea that they could essentially just monetize map scanning with "Scan Modules" in the in-App shop.) I have basically been using the map app more as a unique game mechanic than back when all this stuff started and everyone was using 6 seperate accounts at massive radius to blanket scan cities. I am sure I have missed tons of rares doing it like this but I really just enjoy learning new areas with Google maps and GPS. Spotting something that isnt too far away of a drive is really motivating for learning streets, when I was blanket scanning I missed tons of rares too because they were across the city and there was no possible way to get there in 15mins. It really feels like part of the game using only one scanner and moving it around fairly close to where you currently are, or placing it ahead of a route you are traveling so you dont miss anything when you pass through.
