### ISSUE TITLE
Map display or Niantic error: pokemon disappear in 551+ hours instead of <15 min?

### ISSUE THREAD

**Issue by aquastrike** [mchristopher/PokemonGo-DesktopMap#910]
I found it becomes quite frequent that some pokemons disappear in about 550 hours from the map. Is it a map error or the Niantic error? Some Pokemon however will disappear soon even indicated with 550+ hours, but some stay in the map very long like forever.

**Comment by selfdisplaced** [comment]
Yea I get this too. Hoping for a fix :(

**Comment by NickIxo** [comment]
i find it's gotten worse too. :/

**Comment by pdevacc** [comment]
if you restart or open the stats --> full stats page it will clear the old ones that should have disappeared. Not a true fix, but it makes it easier to see.

**Comment by jccwright** [comment]
I've been sifting through all the code modules and such and I'm curious if the original responses from Niantic are being stored anywhere? If so is there any way to view those because I'm noticing that all the bad displays are having the same date/time stamp: 

![image](https://cloud.githubusercontent.com/assets/13989827/17652288/819c60d2-6246-11e6-9b73-10f17ee7b1ea.png)

**Comment by eluarca1971** [comment]
Hi, as a temporal solution: uninstall Pokemon go Live map. Don't reinstall yet, go to: C:\Users\AppData\Roaming\ there delete the Folder: "Pokemon Go Live Map" there is where the app stores the Access data and the log of pokemon located in the time. once that, reinstall the app and input your acces data (Google Key and coordinates) Note: BEFORE the uninstall be sure that you have write down at least your Google Key) I know that this is a not programming soultion, but at least that give you tme to find the real solution. I hope that this can help you.

**Comment by bpacynski** [comment]
java error 
http://scr.hu/24ri/zsxz6
latest Java version on my Windows system

**Comment by aquastrike** [comment]
This has become a big issue to me, as the screen is full of such "unexpired" pokemon. Relauching the map does not remove such pokemon from the map.  I tried to reinstall the app, it does not work. i am use mac osx. Is there any simple way to delete the log file? I don't know where the log file of the live map was stored. The

**Comment by SeedOfEvil** [comment]
I don't do a while reinstall to fix this issue. 
**NOTE: As far as I know this fix will reset your stats.**
To fix just go ahead and delete this file: %USERPROFILE%\AppData\Roaming\pokemon-go-map\pogom.db
Then start the app again, it will recreate the file and start pretty much from zero, pretty useful when they accumulate when you are not around. Use this when you would like to start fresh.
You can even create a batch file with the del command infront of that path and run it prelaunch.

Hopefully I am of some help.

**Comment by aquastrike** [comment]
@SeedOfEvil Are you using Windows? I use Mac OSX. I couldn't find the directory you pointed out above. thanks for help.

**Comment by SeedOfEvil** [comment]
@aquastrike Yes I am sorry to mention this was only tried on a Windows install.

**Comment by jareem** [comment]
@jccwright which port do you use to connect to db ?

**Comment by wmehanna** [comment]
Same as @aquastrike , i'm under OSX, tried to uninstall the app/reinstall it, and searched for a stat folder anywhere on the disk with no success. Anyone ?

**Comment by cpbeckner** [comment]
Would it be possible to adjust the coding for the Refresh button in the app to have it parse the db and delete any 500hr times....couldn't that be any easy fix?

**Comment by mattrat88** [comment]
Also looking for the Mac directories for this file anyone ??

**Comment by bigorthy** [comment]
Solve for MAC users: Backup your Google API Key and Username as you will need to re-enter.

Hold down Option and click "Go" at the top of your Finder screen. Click on Library.
Then delete this folder (backup first on desktop): **/Users/myusername/Library/Application Support/pokemon-go-map**


PC solve from eluarca1971 above: 

> Hi, as a temporal solution: uninstall Pokemon go Live map. Don't reinstall yet, go to: C:\Users\AppData\Roaming\ there delete the Folder: "Pokemon Go Live Map" there is where the app stores the Access data and the log of pokemon located in the time. once that, reinstall the app and input your acces data (Google Key and coordinates) Note: BEFORE the uninstall be sure that you have write down at least your Google Key) I know that this is a not programming soultion, but at least that give you tme to find the real solution. I hope that this can help you.

**Comment by mattrat88** [comment]
It's not there in app support man

**Comment by foshiz** [comment]
@mattrat88 Are you looking in /Users/YOURUSERNAME/Library/Application Support for the pokemon-go-map folder? I'm using version 0.2.1 of the app that generates this folder. When I deleted this folder the issue went away for me.

**Comment by wmehanna** [comment]
foshiz : sir, you are a hero !

**Comment by mattrat88** [comment]
That's where I'm looking

**Comment by jezcave** [comment]
@foshiz Dude, thank you so much. My lo0cal area was getting so overloaded with 500hr pokemon i could barely see the real ones.

**Comment by aquastrike** [comment]
@foshiz it works! Thanks so much for help.

**Comment by mwoelky** [comment]
I have a cleanup cronjob running.
(*Note*: replace <your.username> with your real mac username in the following!)


### db-Location is on MacOSX 

`/Users/<your.username>/Library/Application Support/pokemon-go-map/pogom.db`


## basically you can view the corrupt entry on Terminal with:

Change to pogomap-Dir: `cd /Users/<your.username>/Library/Application Support/pokemon-go-map/`

### view corrupt entries

`sqlite3 pogom.db "SELECT *  FROM pokemon WHERE disappear_time > Datetime('now', '+60 Minute');"`

### And you can manually correct these entries with

`sqlite3 pogom.db "UPDATE pokemon SET disappear_time = Datetime('now', '+60 Minute') WHERE disappear_time > Datetime('now', '+60 Minute'); SELECT changes() FROM pokemon LIMIT 1;"`

I use 60minutes, because there are some rare valid entries around 60min disappear_time I learned from the discussion at https://github.com/PokemonGoMap/PokemonGo-Map

### so my cron entry (crontab -e) is:

`00 * * * *   (date && /opt/local/bin/sqlite3 /Users/<your.username>/Library/Application Support/pokemon-go-map/pogom.db "SELECT *  FROM pokemon WHERE disappear_time > Datetime('now', '+60 Minute');UPDATE pokemon SET disappear_time = Datetime('now', '+60 Minute') WHERE disappear_time > Datetime('now', '+60 Minute'); SELECT changes() FROM pokemon LIMIT 1;") >>/Users/<your.username>/Documents/fix.pokemonmap.db.log.txt`

I'm logging the cron runs to a file at `/Users/<your.username>/Documents/fix.pokemonmap.db.log.txt`


Hope this helps so you don't have to reinstall PogoMaps again and again till the fix from https://github.com/PokemonGoMap/PokemonGo-Map is incorporated in the next release.

**Comment by Sedare** [comment]
Doesnt actually fix issue, just removes cache of stored spawn locations locked into this glitch.  Removing the folder only resets it, and the scanner still creates new eternity timer pokemons.

Still awaiting the fix.

**Comment by gorbrush** [comment]
https://raw.githubusercontent.com/PokemonGoMap/PokemonGo-Map/0f19c0a85b421a83c5c0d50c6fd39d59c1040f2c/pogom/models.py

Turn off pokemon desktop app.

In Windows copy the text of the above raw text to the clipboard, make a copy the document %appdata%/Local/pokemon/app-0.2.1/resources/app/map/pogom/models.py then open the original with wordpad, copy the contents of the clipboard over the top of everything in models.py and save.

Delete everything in %appdata%/Roaming/Pokemon-go-map to clear the database or leave all the junky 500+ in there to expire if you dont care.

Finished.

Should fix this issue. Creates some other issues but fixes all the junk pokemon clogging up the screen.

**Comment by Dab-Nation** [comment]
Guys, i cannot find said "%USERPROFILE%\AppData\Roaming\pokemon-go-map\pogom.db".

Sorry for being such a "noob" but i checked out my app data and there is nothing in there.

I have the AppData folder up, but there is nothing in the folder. Any help would be much appreciated. Thanks

**Comment by gorbrush** [comment]
Just type %appdata% into windows explorer. It will load the variable location for your actual application data for your user account. Then just follow the folders.

**Comment by gorbrush** [comment]
Actually this might not be working. I left it running for 30 minutes and it may have crashed one of the services.

**Comment by Dab-Nation** [comment]
Cheer for the help found the roaming folder but could  not find the pokemon go map folder. 

Would it make any difference if you used a different version of the scanner or  a different set up? https://www.reddit.com/r/pokemongodev/comments/4wqidn/pogom_is_back_with_the_fastest_map_available/ i used this one.

**Comment by gorbrush** [comment]
Weird. It works for like 30 minutes then just stops processing.

**Comment by gorbrush** [comment]
Ohh cool they have instructions for the git for windows. Screw this I'm installing it manually.

**Comment by anon2019** [comment]
I really think this is IP based by nantic.
