### ISSUE TITLE
Are we at risk of getting banned by using this scanner, since niantec has started this new ban wave?

### ISSUE THREAD

**Issue by Deathstroke10** [mchristopher/PokemonGo-DesktopMap#917]

**Comment by iPaulis** [comment]
Yes. That is why you shouldnt use your main account and then this question becomes irrelevant.

**Comment by TProject1990** [comment]
Doesn't matter which account if it is an IP ban.

**Comment by iPaulis** [comment]
Doesn't matter an IP ban if you have dynamic IP.

**Comment by Deathstroke10** [comment]
do you know how to tell whether you have a static or dynamic IP, and if you have static how would you change it to a dynamic IP?

**Comment by Shogunz1** [comment]
Use this site https://www.whatismyip.com/. Then reboot ur router and reload the site. If ur ip changes then you have a dynamic ip.

**Comment by iPaulis** [comment]
> Use this site https://www.whatismyip.com/. Then reboot ur router and reload the site. If ur ip changes then you have a dynamic ip.

It does not exactly work like that. Sometimes even rebooting your IP doesnt change because your Internet Service Provider assigned an IP to your router/modem for a fixed period of time (like some days or a week).

So static/dynamic IP is given by the ISP, but usually common clients will have dynamic IP, since static IP is an added paid service that only certain clients would need such as companies.

**Comment by Shogunz1** [comment]
Yes I get that but if you load that website, or look at your router settings you should see your current ip address. If you reboot it and you see it change on that website or in the settings you have a dynamic ip. Most newer routers are already set to dynamic just for security reasons right? I could not be following you but you only have one unique ip address from my understanding.

**Comment by Shogunz1** [comment]
Ok wait I see. You have a WAN IP and a LAN IP . The WAN IP changes but the LAN IP is given by your IP. What ip would Niantic be looking at then to decide a ban? Can you contact your IP and request frequent IP changes, or a change in IP?

**Comment by iPaulis** [comment]
No you cant. BTW, the LAN IP is your local IP, the ones your computers/devices in your own network use to identify themselves. The IP that Nyantic blocks is the public IP, the one you can see in the website you shared before.

**Comment by Shogunz1** [comment]
ok ok so if that ip address changes on that website you should be good. just reboot you router every so often? Ty for your knowledge and help.

**Comment by pill0ws** [comment]
If you are going to use this app, you just have to accept that you could be banned. Niantic considers this cheating although it enhances the gameplay in so many way. Surely blanket scanning with multiple accounts is a bit much in terms of "unfair advantages" and that is what they are aiming for with these banwaves. You are likely not going to get banned for using an IV checker but you probably will get banned for playing with an unfair advantage. It has nothing to do with "Terms of Service violation" and everything to do with "Publicity".  I'm going to continue to use the App because It just makes for interesting activities, however I limit myself to only 1 instanace of the App because I feel like interacting with it and moving it around is part of the activity. Just having huge areas show "all of the things" was cool for a bit but it was part of their server issues so I pretty much figured if there were ever a chance I could talk my way out of a ban it's by at least honoring some limitations. I've gained too much real world knowledge from using this App to give it up. The Hippocampus can produce cells late into adulthood, and it is heavily used in spatial memory. Basically exploring literally produces new brain cells, I aint given that shit up.

**Comment by Shogunz1** [comment]
Yeah pill0ws. In my case I'm disabled and cant walk or drive much so I'm limited in what I can do and this program gives me the ability to play it. I just got confused and misinformed on static and dynamic IPs. People were saying that the threat of IP bans are alleviated by having a dynamic IP. So I followed some of their ideas and got confused on the two IPs one has, the WAN IP and the LAN IP. I can change my WAN by just rebooting my router while my LAN IP stays the same. I was wondering which one Niantic looks at to administer bans. Judging by what iPaulis said its ones WAN IP.

**Comment by Shogunz1** [comment]
I maintain three additional PTC accounts and exclude my main. I was just getting concerned with all them being on the same ip and me getting that ip ban.

**Comment by pill0ws** [comment]
They were doing device bans as well in beta. So one new requirement is logging in and doing the tutorial. Once they identify those new accounts as "scan bots" then they wil be able to see metadata for the device they used and can just prevent you from ever playing on that device by denying the device login. They may even be able to tie it back to your main if you logged in to do the tutorial with the same device you play on regularly. If they really wanted to, they could figure out who we all are. Dont forget this game runs on GPS data, they already know where we all live lol. It sure would be a strange coincidence if a banned IP matched the address of a player and only one player lives there at all.

**Comment by MrAwesomers** [comment]
If they ban people for using this, they will lose a lot of players and money. A lot of the people I know quit the game after pokevision stopped their service... My friends keep playing because we drive around with my laptop running 3 instances scanning a 5 (or smaller) radius and we hunt pokemon. If they force us to walk/drive around hoping to ever find anything better than a horsea, they should just sell everything they own now and let someone who wants players to enjoy the game take over.

I can understand them trying to stop botting, but they destroy the good stuff that helps the normal players like pokeadvisor, pogoprofiles and scanners like this one while botting returned like nothing happened. If they ban my main account, I'd probably use a bot to to get my level and pokemon back instead of restarting at level 1.

Also, people that run more than 10 instances of scanners are probably the reason they don't allow stuff like this. I've seen someone run 60 instances to scan entire countries...

Niantic, use your brain and stop cheaters.. Not things that improve your game! Learn from other companies. Just like people install a tweaked OS to their devices to fix flaws or to tweak things to their needs until the companies implement those changes themselves, until you are satisfied enough to not want to change anything anymore.

**Comment by pill0ws** [comment]
Yea, I mean to be fair, originally I think we all were running multiple scanners. I actually was having all kinds of technical issues with my devices crashing or not being able to get the mobile tunnel to work, or when using a laptop it would blow a fuse in my car, etc. so when you could scan that much, I stayed at home mostly and played with the app rather than take as full advantage of scanners when they were unrestricted. I logged tons of data knowing that theyd eventually kill it because ultimately that level of scanning really was a bit much. Post update I still ran 5 for a bit but eventually got tired of setting them up so much. Now I just use one and I play with it a lot. It gives me all kinds of ideas for content they could just add to make the game more fun and engaging while still giving the players what the want to some degree. Finding a rare while using just one scanner is very rewarding, they arent exactly as easty to find as they were. Also dropping a scanner when you find somehthing cool nearby just removes all the crappy wandering and staring at the phone. I peek at Google maps, check so roads and the time left to see if I can even make it. Then do nothing but pay strict attention to tracffic, road signs and other cars because I am usually going someplace I have never been before... and I've lived in this city for 2 years. Basically probing around until you find something you are trying to collect a bunch of is like finding a quest objectives. They could introduce a quest system as well as a system for training your own pokemon to go out and help you find others, that could be a fun alternative to Gym battling that actually lets you utilize things that you caught for the part of the game you enjoy the most. I they could completely eliminate the need to scan by introducing the mechanics to the game in a fun way that has limitations but also rewards. Like, just a simple example for gameplay embracing this : You can train pokemon to be hunting pokemons (like a hunting dog) and whatever type you train may be good at seeing out rares for the same types it counters in combat. 

Another thing they could do if they embraced map scanning mechanics for gameplay is quest sytem or something. Lets say you can get quests at Gyms you control and they let you choose a rare type, or maybe even a specific pokeon depending on gym level and then tell you when one pops up somewhere in town. They could even use this system to discourage driving, maybe in order to use your hunting pokemon you can't trigger pokemon encounters yourself but you can send them out while you are on your way to the store and then check back with the, or maybe you simply can only see pokemon on the google map. or maybe when you are driving rather than playing, you can admit to it and then get some kind of credit toward training your pokemon to hunt others. They'd totally incentivize "not driving and playing" through a reward that can only be recieved above a certain speed and can let you do something fun with your favorite pokemons

**Comment by Deathstroke10** [comment]
Can they still ban your IP if youre using a google account instead of a PTC account?

**Comment by iPaulis** [comment]
The account is how you identify with the game, the IP is how your internet conection is identified in the global internet network. They can both ban your accounts and/or your IP. If they ban your account you can create another one and start again. If they ban your IP you wont be able to play with any account until your IP changes. The one who provides the IP is your network provider, and one way to refresh your IP would be to reset or resync your router/modem so the network provider gives you a new IP. However, it does not always work that way, because usually network providers assign IPs with a certain lifespan, you can try to force them though.

**Comment by Deathstroke10** [comment]
iPaulis doesn't a vpn protect your IP address?

**Comment by romanticheart** [comment]
Have we heard of any instances of someone's IP being blocked? Or are we just discussing this as a "Niantic can do this if they choose to" kind of deal? 

Personally I don't think they would go the route of banning IP's. They run the risk of banning entire college campuses, apartment complexes, hotels. There are lots of instances where a large group of people share IPs and I feel like that would make Niantic avoid that route.

**Comment by Psykoflo** [comment]
I know someone handling another radar tool, his IP's (using a VPN) are often ban, but from what I've heard, it seems that it was only Soft bans.

**Comment by iPaulis** [comment]
Yes, VPN would protect your IP but only because in practice you are using a different IP (the one from the VPN). Once that would be banned, you would not be able to use that VPN again.
They have already banned IPs from faculties, and they had to request nyantic to unblock them.
