### ISSUE TITLE
Wondering how many accounts everyone is running

### ISSUE THREAD

**Issue by Shogunz1** [mchristopher/PokemonGo-DesktopMap#920]
Title..

**Comment by FirelordPhoenix** [comment]
Just one, and maybe zero from now on because I'm worried about the new ban waves coming.

**Comment by pill0ws** [comment]
I just use one and I already use it very sparingly. I also use it in a manner that I would consider "fair" and not cheating. The changes made to the API make one scanner App tunneled to a mobile device into a game mechanic that improves the experience of the game. I'm still not pleased with the amount of visual feedback in the game world for pokemons existence at all (the even removed rustling grass). The map app essentially generates a "quest" system that the game does not have. It literally adds fun gameplay to the game by creating objectives rather than having you wander around. It is an amazing learning tool as you can immediately reference Google Maps for information on the area and what may of drawn a rare pokemon or one uncommon to your region. It is also great motivation to not only get out of the house but to explore new places that you have never gone before because there is an objective there (I'm trying to get as many gastly or abras as I can and often will put them above all else). It also sort of makes driving into a competely different meta game, rather than driving around and dangerously capturing pokemon while doing so, you probe around until a "quest" is discovered and then must navigate your way there to capture it (you can always park when you get there). 

So I plan on using the app in a manner that improves gameplay and would be hard to consider "cheating". especially with the API restrictions finally in place. I toggle it on and off when not actively catching pokemon, I force it to adhere to its own travel time rather than teleport it around and I use it to scan my current area or an area I am already traveling toward and I use it to learn routes, cool hang out spots and local businesses that I would of never known existed without  integrating Google maps into the gameplay of a game build of data from google maps. I think of the scanner as one of my pokemon that I have chosen to scout for me. In terms of gameplay, that is exactly what it is when enforcing some limitations and because I think it should actually be an official part of the gameplay I will continue treating it as a friendly invisible critter that I send out and order around to different places and tells me if there is a quest objective there. Imagine if this was an actual thing you could send pokemon you have captured out to do and if there was a whole meta game to gaining wild pokemons affection so they could go search in areas that only their types can search or even try and locate a specific pokemon that only they are good at locating. I may as well start writing up my ban appeal right now so I can proofread it enough to make sure they know why I continued doing this under the threat of a permban. Which comes down to "Learning is fun, seeing new stuff is fun, the app motivates exploration and inquiry that the games wander system lacks"

**Comment by mg6101** [comment]
I'm running 4. But none of them are my main account. I haven't gotten banned yet (***knocks on wood***)

**Comment by selfdisplaced** [comment]
1 on a dummy account. I use it to supplement the terrible in game tracking and I'm a rural player, so it's hard to find stuff around me without it.

**Comment by ejd59005** [comment]
i use 2 accounts, on a VPS

**Comment by Regulator69** [comment]
i have a main, and my dummy is strictly for computer use and dont use it for mobile use esp on same phone just in case they link IP or anything

**Comment by rhawley88** [comment]
how are you guys running multiple accounts used to be able to but now when i have 2 running whichever marker was moved last is the one that scans the other just sits there
