### ISSUE TITLE
SQL to manually fix 600hr bug

### ISSUE THREAD

**Issue by alangerow** [mchristopher/PokemonGo-DesktopMap#934]
Using DB Browser for SQLite (http://sqlitebrowser.org/) I was able to open the PokemonGo DesktopMap SQLite DB file and construct a SQL statement to update the 600hr Pokemon so they don't appear, but keeping them in the database for data mining to find spawn points or sightings. You can run this script whenever you have a bunch of Pokemon that are going to expire in a few weeks, instead of minutes.

Update the file /Users/[your username]/AppData/Roaming/pokemon-go-map/pogom.db

Using this SQL
`update pokemon`
`set disappear_time = datetime('now')`
`where disappear_time > datetime('now','+1 day')`

You'll have to restart the program if you update the database while it's running.

**Comment by mattaereal** [comment]
I did the same thing on linux via CLI and I confirm this fixes it.

File pogom.db is on ~/.config/pokemon-go-map.

# sqlite3 pogom.db
update pokemon
set disappear_time = datetime('now')
where disappear_time > datetime('now','+1 day');

And restart the app.

**Comment by ohiotech** [comment]
If I understand correctly, #934 will clear my existing timer issue and allow me to keep the spawns without losing the spawn points and important data saved for mining purposes. For this, thank you. I'll test within a couple of hours and add additional confirmation regarding personal success... or lack thereof. 

Would you happen to know if this can be combined with #935? Ideally I'd like to be able to remove existing and prevent new. If I understand correctly, #935 prevents it from happening moving forward.

**Comment by alangerow** [comment]
I just did #935 and it worked for me. So you would do that to fix the map. Their instructions involved removing the pogom.db file to get rid of the bad data. My SQL script can be used after to instead keep your data, and not have the bad ones show up anymore. But you keep all of your data to mine for patterns in case these applications stop working for good, or find where to go to hunt.

**Comment by ohiotech** [comment]
Because I want to get it right... 935 first and then 934, or visa versa. I'm prepping for 935 now.

**Comment by alangerow** [comment]
Either way, doesn't really matter. I was doing it manually before the fix, and just do it before and then don't run the app until it's updated, or run it after. Until you run it, the bad spawns will still show.

**Comment by cabernal4** [comment]
Thanks for this, can confirm it works on mac.
pogom.db is located in /Users/{user}/Library/Application Support/pokemon-go-map/pogom.db
I could not get finder to reveal the hidden folders when trying to add the db to sqllitebrowser so i had to make an alias and put it in the desktop.

**Comment by ohiotech** [comment]
Either way, you're Amazing! Thank you. So you know, I know squat about DB Browser for SQLite. Never ran this before today. Don't know how to execute a command to save my life, but your script, and knowing that I needed to open the db, find where to execute the commands, and I did, as well as write the changes to the DB were relatively easy to find since the utility is relatively intuitive for that.

Too bad I got home and all 3 of my accounts were banned. At least I got to see about 800 spawns populate my screen in one instance, and then vanish after I ran it again. I'll be running 935, sans deleting my db, to make sure it works moving forward. And yes, I backed up my previous db just in case I bunk 935 up. But as for yours? Thumbs up!

**Comment by sirrjames** [comment]
I can't seem to figure this out, I am using a windows 7 PC.
Screen shot below
![image](https://cloud.githubusercontent.com/assets/21068908/17733354/254f65c2-6444-11e6-9b60-117ae43429ba.png)

**Comment by justinblayney** [comment]
Hello,
I did this on OSX, now it is stuck on waiting, won't load pokemon

**Comment by alangerow** [comment]
@sirrjames This is where you do the work: 
![image](https://cloud.githubusercontent.com/assets/20896440/17739151/61b847ec-6451-11e6-9629-289c35c1cff3.png)

**Comment by alangerow** [comment]
@justinblayney make sure you close the DB file before opening the application. You may be getting an error that the DB file is locked. I had that happen to me. Just close the DB program, and restart the application.

**Comment by justinblayney** [comment]
i tried with a new account, that one works i did get banned

**Comment by justinblayney** [comment]
I do appear to be banned, stuck on waiting with old account, a new account scans fine.  I have restarted, rebooted, logged in multiple times with both to confirm this. I do not know for sure that it is related to doing this, but this is when i noticed it. Good thing I used a fake account for this

**Comment by mattaereal** [comment]
This has absolutely nothing to do with the game account management, nor Niantic bans. It's just a simple query to the local database to remove the pokemons with bugged disappear time.

**Comment by sirrjames** [comment]
@alangerow 
So once I run it, I am good to go? I only have to do it that one time?

**Comment by mattaereal** [comment]
This is not a permanent fix. This just tells the database, where all the pokemons that the app saw appear are persisted, to delete the ones that are bugged. You have to run this everytime you accumulate a considerable amount of pokemons that are bothering your map view.

To be more specific, if I understand correctly the query, this selects all the pokemons on the database, and updates the disappearing time to the actual time, meaning that they will simply vanish on execution, to all the pokemons which have a disappearing time higher than a day. Pokemons with disappearing time higher than a day should not exist since the highest disappearing time is 15 minutes as far as I know.
