### ISSUE TITLE
Ban, never left local area

### ISSUE THREAD

**Issue by kla007** [mchristopher/PokemonGo-DesktopMap#965]
I used this map program a lot but I never left my local area, and when I did it would be within 50 miles of my house and I would "travel" at normal speeds.
Now when I attempt to login I get: "Unable to load game data from game server"
I'm assuming it's banned but I want to avoid future bans... do the API requests along with
logging into your account cause the bans?

**Comment by andrei-gheorghiu** [comment]
Using this app violates the Niantic PoGo's terms and agreements (which you have to agree with in order to play the game). Niantic is free (and likely) to ban any account or any device that uses this software, unless this software will develop a "noise" pattern, like, for example, instead of geometrically perfectly overlapping circles to scan an area (which is highly detectable once Niantic searches for the pattern, which they haven't yet), it could instead add a little noise, so the distances between the span points are never equal, making the pattern much harder to detect. Another good "noise" option would be to add some noise to the scanning interval.

But NOBODY should use this software on their main account. Once the scanning pattern will be searched for by Niantic, it is most likely every account that has it in their history to be banned. I'm surprised nobody read the EULA. 

And, to be technically correct, Niantic can delete any account at any time without providing a reason at all.

**Comment by Ang41187** [comment]
@andrei-gheorghiu Should we be making a dummy Google account to,make the API key? Also how do we go about adding the "noise"?

**Comment by andrei-gheorghiu** [comment]
@Ang41187 I made a brand new Google account for this. I also plan on using a device from work (that is not otherwise used for gaming and it's not personal) to catch a few pokemons because I expect Niantic to also ban accounts that only walk around without ever catching a pokemon. About the noise, it's just an idea on how we could mingle mapping accounts so Niantic wouldn't find them with trivial queries. I haven't actually tried to change anything in this app and, knowing myself, I will only do that once it stops working. :)
