### ISSUE TITLE
Ban discussion

### ISSUE THREAD

**Issue by Shogunz1** [mchristopher/PokemonGo-DesktopMap#973]
So just wondering what the consensus is. How many people have experience the IP Bans? Anyone have their main accounts banned? Just wondering if that's possible even if you run electron with other accounts than your main. From what I've been reading Niantic just bans the accounts using the tracker. I've had my two old ones banned but that was before the update.

**Comment by pill0ws** [comment]
I'm a bit curious on this as well. I have been using this app acceptng that I could be banned because of the drastic improvement in gameplay that just one instance of the app provides. The things you can do to cheat in this game are insane levels of cheating. When I learned about Pokemon Sniping I was like "Wow! they can do that?" I kinda take a little pride in that I have had to visit all these places that I would of never even of thought to just walk had I not had the aid of something giving me knowledge of a goal that existed there. Just today even, saw a Gengar on the nearby tracker for the first time ever. I was visting a college and it was actually off the main road and out on a nature trail. I would not of thought to check out on that trail for a second, just the idea of "well if I am wrong, then I waste all that time walking out there and it despawns." but I knew it was out there and walked my butt out into the middle of the woods to nab a Gengar (crappy IV but I found an awesome new bike riding spot).

I still havent had my IP banned and I still havent had my fresh PTC account that I made banned, although the first account I had has been banned (I used it for months and back when you could beehive scan huge areas in 15 mins.) Lately I have been turning the scanner on only when I need it. Toggling it on and off and never letting it restart a cycle by teleporting. One thing I REALLY like it for is follow currnet location so while I am capturing a pokemon I can still know what pokemon are around me, this is a big deal. So I hope that they distinguish the difference in levels of cheating if they actually do start taking action against main accounts. A suspension would deter cheating more than a ban, if I get banned and still feel an urge to play this game, I likely will not care what happens to any account after this one. It's pretty much open season on doing everything I deplore to catchup another account to my current legitly played one (I just cant accept using one app is cheating, the game needs less staring at a screen and more destination objectives)

**Comment by dhyde79** [comment]
I got one banned saturday morning...got off work at about 0600, headed home, knew I was going to do some hunting on my way (wife and kid were out of town and I had nothing to do but sleep) so I teamviewered into my PC and launched the app with my alternate gmail account, I don't recall why I used that instead of my PTC account, but....I did...
went out, hunted for less than an hour, got home, checked locally, and then went to the throne room, and went to plug my phone in, forgot to go kill the scanner...got an email at 11:44 from niantic stating that my account has been terminated, permanently, unless I choose to appeal it.  I may, just for S&G to see what they do, but, if you'd like, I'll happily post the contents of the ban notice for all to see....

**Comment by conklin75** [comment]
I may have just gotten my main account banned despite rarely using it for this app but I never spoofed/botted/logged in to anything else so I'm pretty sure it was this

**Comment by dhyde79** [comment]
why would you use your main account?

**Comment by conklin75** [comment]
Don't anymore but I did initially before api changes and haven't done anything else ban worthy. I didn't expect this to actually be an issue for niantic I figured spoofing and botting were more important but whatever I was almost at a full pokedex and was getting sick of it anyway
