### ISSUE TITLE
"Waiting.." after login :(

### ISSUE THREAD

**Issue by ultimate2106** [mchristopher/PokemonGo-DesktopMap#979]
Well.. after I logged in it's not scanning, instead it's "Waiting.." the whole time. I created new Google Project for API Key and new PTC Account, tried to login via google and reinstalled the program. Still nothing happens.. is the api broken again?

EDIT (Console Log):
server up: null
main.html:146 Error getting location, trying second provider PositionError
main.html:148 Found location [50.1167,8.6833] by ipinfo.io
main.html:173 Python server started!
main.html:173 Got open express port: 8001
main.html:173 Express server started!
main.html:158 server up: http://localhost:8001
main.html:168 2016-08-22 12:41:17,213 [ search_worker_0][      auth_ptc][    INFO] PTC User Login successful.
2016-08-22 12:41:17,213 [ search_worker_0][      auth_ptc][    INFO] Request PTC Access Token...

main.html:168 2016-08-22 12:41:17,382 [ search_worker_0][      auth_ptc][    INFO] PTC Access Token successfully retrieved.

main.html:168 2016-08-22 12:41:17,417 [ search_worker_0][        pgoapi][    INFO] Creating a new direct request...

main.html:168 2016-08-22 12:41:17,417 [ search_worker_0][        pgoapi][    INFO] Adding 'GET_MAP_OBJECTS' to RPC request including arguments

main.html:168 2016-08-22 12:41:17,418 [ search_worker_0][        pgoapi][    INFO] Execution of RPC

main.html:168 2016-08-22 12:41:17,959 [ search_worker_0][        pgoapi][    INFO] Cleanup of request!

main.html:168 2016-08-22 12:41:17,960 [ search_worker_0][        search][   ERROR] Search step 1 map parsing failed, retrying request in 10 seconds. Username: GreetingsFriend7
Traceback (most recent call last):
  File "C:\Users\laura\AppData\Local\pokemon\app-0.2.1\resources\app\map\pogom\search.py", line 254, in search_worker_thread
    parse_map(response_dict, step_location)
  File "C:\Users\laura\AppData\Local\pokemon\app-0.2.1\resources\app\map\pogom\models.py", line 326, in parse_map
    cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']
KeyError: 'map_cells'

main.html:168 2016-08-22 12:41:27,997 [ search_worker_0][        pgoapi][    INFO] Creating a new direct request...
2016-08-22 12:41:27,997 [ search_worker_0][        pgoapi][    INFO] Adding 'GET_MAP_OBJECTS' to RPC request including arguments

main.html:168 2016-08-22 12:41:27,997 [ search_worker_0][        pgoapi][    INFO] Execution of RPC

main.html:168 2016-08-22 12:41:28,355 [ search_worker_0][        pgoapi][    INFO] Cleanup of request!
2016-08-22 12:41:28,358 [ search_worker_0][        search][   ERROR] Search step 1 map parsing failed, retrying request in 20 seconds. Username: GreetingsFriend7
Traceback (most recent call last):
  File "C:\Users\laura\AppData\Local\pokemon\app-0.2.1\resources\app\map\pogom\search.py", line 254, in search_worker_thread
    parse_map(response_dict, step_location)
  File "C:\Users\laura\AppData\Local\pokemon\app-0.2.1\resources\app\map\pogom\models.py", line 326, in parse_map
    cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']
KeyError: 'map_cells'

**Comment by outofchocolate** [comment]
After you created an account, did you catch a first pokemon and set up a nickname? That has worked for people so far.

**Comment by ultimate2106** [comment]
Well, I haven't done that with my old Account either.. so that can't be the problem :/

**Comment by Borys74** [comment]
Since this morning I have the same problem. When I run the map, all the time I have 'Waiting' and the program does not scan the selected location. The last time I used the program on Friday and then work properly. Perhaps the recent changes introduced by the Niantic also changed the API.

**Comment by tsourbier** [comment]
I had this problem with my PTC account for a few days (things kept working fine w/ Google login) then I got an email today saying my PTC account got suspended (fair enough...).

T.

**Comment by Borys74** [comment]
Ok. With a Google account everything works properly. Thank you for your help.

**Comment by pidgeyparmesan** [comment]
This is my issue as well, except I haven't received an email stating whether I was banned or not. The program seems to work fine on a different computer with a different account of mine but we'll find out once it has logged off if it's still working. 

Maybe it was Niantic who changed the API after yesterday.

**Comment by ejd59005** [comment]
You're probably banned. Happens all the time. Just make a new PTC account and use that one

**Comment by MynameisDiego** [comment]
That happened to me when I tried to run the application on the computer at my university. In my personal computer that does not happen. Maybe there are some required files that are not installed on your PC.

**Comment by Mutantx** [comment]
I had the "waiting" issue when logging into gmail but it worked for the pokemon trainer account. Not sure if my gmail was banned or if it was just a server issue

**Comment by ultimate2106** [comment]
>That happened to me when I tried to run the application on the computer at my university. In my personal computer that does not happen. Maybe there are some required files that are not installed on your PC.

It's still the same PC..

**Comment by ultimate2106** [comment]
So to make sure you guys know everything:
1. I had an account that worked fine till yesterday even without going into the game and choose a name or pokemon. Now I got the "Waiting.." issue
2. I made a new Account and still the same problem.
3. Tried with new Google API on both accounts. Still the same problem.
4. It's still the same PC and I even tried the new 3.1 Map
5. I even mad a new google account in case that it's banned but nothing changed

**Comment by ejd59005** [comment]
You're IP Banned. Happens to me from time to time

**Comment by ultimate2106** [comment]
> You're IP Banned. Happens to me from time to time

How to fix that?

**Comment by RyusuiJL** [comment]
FWIW, I was getting the "Waiting" issue with my PTC account for about a week before I got the "your account has been terminated" email.

**Comment by ultimate2106** [comment]
Now I created a new PTC, accepted the PoGo TOS on my profile and I'm using CyberGhost to hide my IP. Still "Waiting.." =(

**Comment by FakacX** [comment]
Hi -> your problem is solved here #970

Our manual (Repo)

Hi everybody,

i was participated with @Ruuzha on this problem solving. We used same version of a PoGo Map client and we had same Error logs in console. This problem appeard at thuesday evening on CzechRep servers.

We tried everithing before we discover right PoGo Map setting as he said at top.

And here it is -> If you got the same error message in your Application, maybe this could help you.

1) Start with clear installation of PoGo Map client (When im writing this, is possible to download ver.0.2.1) / or you can yous your actual version but PowerShell scrip may collide with the app version (check it bellow)

2) Read and follow instructions in this thread -> #967 (THX guys -> you made realy good job and all of you got big peace on this problem solve!)

3) I´m recommending to use for Step 2 this PowerShell script which was written by @dodsky (Thx -> worked fine for us), but if u make changes from step 2 mannualy continue by steps 5 and etc... of our manual

Created a short powershell script that follows the steps in case I need to repeat the steps later, tested it locally and it worked. Just create a .ps1 file on windows and paste the following. Check the versions in code before blaming me. :D
`
$map_folder = "$env:LOCALAPPDATA\pokemon\app-0.2.1\resources\app\map"
$map_old_folder = "$env:LOCALAPPDATA\pokemon\app-0.2.1\resources\app\mapOld"

Rename-Item $map_folder mapOld

New-Item -ItemType directory -Path $map_folder

$clnt = new-object System.Net.WebClient
$url = "https://github.com/PokemonGoMap/PokemonGo-Map/archive/v3.1.0.zip"
$file = "$env:temp\map.zip"
$clnt.DownloadFile($url, $file)

$shell_app=new-object -com shell.application 
$zip_file = $shell_app.namespace("$file\PokemonGo-Map-3.1.0") 
$destination = $shell_app.namespace($map_folder) 
$destination.Copyhere($zip_file.items())

Copy-Item -Path "$map_old_folder*.*" -Destination $map_folder -Recurse -Force

Copy-Item -Path "$map_old_folder\pogom\pgoapi" -Destination "$map_folder\pogom" -Recurse -Force

Remove-Item "$env:APPDATA\pokemon-go-map\pogom.db" -ErrorAction Ignore
Remove-Item "$env:APPDATA\pokemon-go-map\Cache\" -Recurse -ErrorAction Ignore
Remove-Item "$env:APPDATA\pokemon-go-map\Local Storage\" -Recurse -ErrorAction Ignore
`

4) As @Dodsky said -> Copy and paste this script in to Notepad and Save it as ".ps1" file right next by file with unofficial 3.1.0 zip which you downloaded in step 2 -> Right click on this .ps1 file and chose Run with PoweShell

5) Lets make thing happend and after continue with usually known procedure (generate your new API key and Create fake account on PTC) -> we recommend to use fake Google mail and PCT accounts!.

6) After you successfully create and verifies your new PTC account go in to the account setting in PTC portal and agree with Therm Of Use (TOS)

7) Log in to game and catch one Pokemon (as usually we recommend to use different mobile/tablet device then the device where you want to play the game, Niantic can catch you and ban can comes...)

8) Log in to PoGo Map application -> if the status is Operating you made it!

So it looks like Niantic made some changes in the game mechanics without some hard changes in game API. They just let the new account search for pokemons after a first pokemon pick in the game. It can be a rly good tactic when you want to block fakers.

Thx @Ruuzha and everybody in the other threads for they´r job.

We was pretty sad without the map.

Good night

**Comment by FakacX** [comment]
It seems like our problem..... resolve is simple -> log in to your fake PTC accout to the game and chatch the first pokemon.... ( i recommend to use different device) -> after that log in to PoGo Map apl and you could have it -> Operational

**Comment by ultimate2106** [comment]
> It seems like our problem..... resolve is simple -> log in to your fake PTC accout to the game and chatch the first pokemon.... ( i recommend to use different device) -> after that log in to PoGo Map apl and you could have it -> Operational

Didn't work

**Comment by ultimate2106** [comment]
> Hi -> your problem is solved here #970

I'll try this one. thx

**Comment by FakacX** [comment]
Yop.... we know :D PLs give us like ;)
