### ISSUE TITLE
Second wave of bans target scanning..

### ISSUE THREAD

**Issue by Shogunz1** [mchristopher/PokemonGo-DesktopMap#994]
Just letting everyone know what's going on. Seems like the latest update brought with it a big ban towards scanners. I've had all of mine banned, made a new one tonight and its working fine atm. VPNs are getting banned too so if you decide to get on a VPN don't waist your time Niantic is hitting them hard. That explained why I could get Operational on my standard dynamic wifi and not my VPN. Everytime I cut my VPN on I got Waiting. I wonder if this means it's going to be that much harder to do this. Making a new account every day might become teadious. All of this probably could have been avoided if they had the damn tracker working right the first time.

**Comment by Mirx** [comment]
A new android version was just released, so they probably just changed some stuff on the API.

Patch Notes

    Implemented Pokémon Appraisal: Trainers will now be able to learn about a Pokémon’s attack and defense capabilities from their Team Leader (Candela, Blanche or Spark) to determine which of their Pokémon have the most potential for battle.

    We are still working hard on several new and exciting features to come in the future of Pokémon GO.

    Minor bot fixes

    r

**Comment by Mirx** [comment]
The scan account I was using was also "banned" last night.

Trying to get into the app with Bluestacks and the latest APK gives me an "Unable to authenticate". Logging in with a different account works.

So it doesn't seem to be version / API related, because then in the app it should still work.
Guess I'll try again tonight to see if it was a backend problem, or guess I'll see how long the other account keeps working.
